<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use App\Models\Advertisement;
use Illuminate\Support\Str;

class AdvertisementsSeeder extends Seeder
{
    /**
     * Startowe ogłoszenia platformy.
     * Email zarządzania: test@test.pl
     * Zdjęcia dodaj ręcznie przez panel /zarzadzaj
     */
    public function run(): void
    {
        $ads = [

            // ══════════════════ WARSZAWA ══════════════════

            [
                'title' => 'Billboard jednostronny - ul. Modlińska, Białołęka',
                'type' => 'billboard',
                'location' => 'ul. Modlińska 223',
                'city' => 'Warszawa',
                'region' => 'mazowieckie',
                'latitude' => 52.3156,
                'longitude' => 20.9887,
                'description' => "Mam wolny billboard przy Modlińskiej na Białołęce, wyjazd w stronę Nieporętu. Dużo aut rano i po południu, bo ludzie dojeżdżają z tamtych okolic do pracy. Sam mieszkam niedaleko i powiem szczerze — każdy kto jedzie tą drogą mija ten baner. Minimalny wynajem miesiąc, cena do ustalenia przy dłuższej umowie. Kontakt przez formularz.",
                'price' => 1400,
                'price_unit' => 'month',
                'width' => 5.04,
                'height' => 2.38,
                'variant' => 'standard',
                'road_class' => 'urban',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['car'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'price_negotiable' => true,
                'environment' => 'urban',
            ],
            [
                'title' => 'Ekran LED - ul. Głębocka / Targówek',
                'type' => 'led_screen',
                'location' => 'ul. Głębocka 13',
                'city' => 'Warszawa',
                'region' => 'mazowieckie',
                'latitude' => 52.2872,
                'longitude' => 21.0743,
                'description' => "Oferujemy czas antenowy na ekranie LED przy ul. Głębockiej na Targówku. Nośnik zlokalizowany przy skrzyżowaniu z długim cyklem sygnalizacji świetlnej, co przekłada się na ponadprzeciętny dwell time dla kierowców. Parametry: rozdzielczość Full HD, automatyczna regulacja jasności, praca 24/7. Dostępne pakiety: wyłączność dobowa, emisja w rotacji (do 6 klientów). Minimalna długość kampanii: 2 tygodnie. Zapraszamy do przesłania zapytania.",
                'price' => 3200,
                'price_unit' => 'month',
                'width' => 6.00,
                'height' => 3.00,
                'resolution' => '1920x1080',
                'pixel_pitch' => '8',
                'brightness' => '6000',
                'ambient_light_control' => true,
                'traffic_intensity' => 'medium',
                'traffic_type' => ['car', 'pedestrian'],
                'has_backlight' => true,
                'offer_type' => 'agency',
                'variant' => 'standard',
            ],
            [
                'title' => 'Citylight - przystanek Kondratowicza / Bródno',
                'type' => 'citylight',
                'location' => 'ul. Kondratowicza 37',
                'city' => 'Warszawa',
                'region' => 'mazowieckie',
                'latitude' => 52.2803,
                'longitude' => 21.0612,
                'description' => "Wiata autobusowa przy ul. Kondratowicza, przystanek jest tu bardzo ruchliwy bo obsługuje kilka linii z Bródna. Citylight podświetlany, format 120x180. Dużo ludzi czeka tu na autobus zwłaszcza rano. Interesuje mnie najem miesięczny lub dłużej.",
                'price' => 850,
                'price_unit' => 'month',
                'width' => 1.20,
                'height' => 1.80,
                'variant' => 'single_sided',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['pedestrian'],
                'has_backlight' => true,
                'offer_type' => 'owner',
            ],
            [
                'title' => 'Billboard - ul. Płochocińska / wyjazd z Warszawy',
                'type' => 'billboard',
                'location' => 'ul. Płochocińska 85',
                'city' => 'Warszawa',
                'region' => 'mazowieckie',
                'latitude' => 52.3089,
                'longitude' => 21.0534,
                'description' => "Billboard przy wyjeździe z Warszawy w stronę Marek i Legionowa — ulica Płochocińska. Sporo aut wcześnie rano i późnym popołudniem. Jednostronny, format 504x238 cm, oświetlony. Dobry na lokalną firmę albo dewelopera z tamtych okolic. Piszcie na formularz.",
                'price' => 1100,
                'price_unit' => 'month',
                'width' => 5.04,
                'height' => 2.38,
                'variant' => 'standard',
                'road_class' => 'urban',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['car'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'price_negotiable' => true,
                'environment' => 'urban',
            ],

            // ══════════════════ KRAKÓW ══════════════════

            [
                'title' => 'Billboard - ul. Półkole / Nowa Huta',
                'type' => 'billboard',
                'location' => 'ul. Półkole 18',
                'city' => 'Kraków',
                'region' => 'malopolskie',
                'latitude' => 50.0769,
                'longitude' => 20.0521,
                'description' => "Wstawiłem billboard przy Półkolu w Nowej Hucie jakieś 2 lata temu i teraz go udostępniam. Dużo aut tamtędy jedzie bo to dojazd z osiedli do centrum i do obwodnicy. Oświetlony od zachodu słońca, stan dobry. Odezwijcie się przez wiadomość to dogadamy szczegóły.",
                'price' => 1300,
                'price_unit' => 'month',
                'width' => 5.04,
                'height' => 2.38,
                'variant' => 'standard',
                'road_class' => 'urban',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['car'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'price_negotiable' => true,
                'environment' => 'urban',
            ],
            [
                'title' => 'Citylight - przystanek os. Piastów, Kraków',
                'type' => 'citylight',
                'location' => 'os. Piastów 52',
                'city' => 'Kraków',
                'region' => 'malopolskie',
                'latitude' => 50.0812,
                'longitude' => 20.0253,
                'description' => "Mam citylight na przystanku przy os. Piastów w Nowej Hucie. Dużo starszych mieszkańców i dojeżdżających do pracy — przystanek obsługuje linie tramwajowe i autobusowe. Cena za miesiąc z wliczonym utrzymaniem. Jak chcesz dłużej to negocjujemy.",
                'price' => 750,
                'price_unit' => 'month',
                'width' => 1.20,
                'height' => 1.80,
                'variant' => 'single_sided',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['pedestrian'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'price_negotiable' => true,
            ],
            [
                'title' => 'Ekran LED - ul. Kamieńskiego / Podgórze',
                'type' => 'led_screen',
                'location' => 'ul. Kamieńskiego 11',
                'city' => 'Kraków',
                'region' => 'malopolskie',
                'latitude' => 50.0284,
                'longitude' => 19.9623,
                'description' => "Agencja AdPoint udostępnia powierzchnię na ekranie DOOH przy ul. Kamieńskiego w Krakowie-Podgórzu. Lokalizacja przy węźle tramwajowym, szacowany dzienny OTS: 8 000–11 000 osób. Profil odbiorcy: mieszkańcy rozwijającej się dzielnicy, pracownicy pobliskich biur i usług. Ekran pracuje całą dobę z automatyczną optymalizacją jasności. Możliwość zakupu emisji w modelu tygodniowym lub miesięcznym. Szczegółowa oferta i media kit dostępne po kontakcie.",
                'price' => 2800,
                'price_unit' => 'month',
                'width' => 4.00,
                'height' => 2.50,
                'resolution' => '1280x720',
                'pixel_pitch' => '10',
                'ambient_light_control' => true,
                'traffic_intensity' => 'medium',
                'traffic_type' => ['car', 'pedestrian'],
                'has_backlight' => true,
                'offer_type' => 'agency',
                'variant' => 'standard',
            ],

            // ══════════════════ WROCŁAW ══════════════════

            [
                'title' => 'Billboard - ul. Kosmonautów / Fabryczna',
                'type' => 'billboard',
                'location' => 'ul. Kosmonautów 51',
                'city' => 'Wrocław',
                'region' => 'dolnoslaskie',
                'latitude' => 51.0989,
                'longitude' => 16.9823,
                'description' => "Powierzchnia reklamowa przy ul. Kosmonautów we Wrocławiu, w bezpośrednim sąsiedztwie wjazdu na obwodnicę i trasę do autostrady A4. Nośnik dwustronny 6x3m skierowany na ruch w obu kierunkach — centrum oraz węzeł autostradowy. Profil ruchu: mieszany (osobowy, dostawczy, ciężarowy). Oświetlenie LED, ekspozycja całodobowa. Nośnik zarządzany przez Grupę Reklam Zewnętrznych Południe Sp. z o.o. Minimalna umowa: 1 miesiąc. Faktura VAT.",
                'price' => 2600,
                'price_unit' => 'month',
                'width' => 6.00,
                'height' => 3.00,
                'variant' => 'two_sided',
                'road_class' => 'urban',
                'traffic_intensity' => 'high',
                'traffic_type' => ['car'],
                'has_backlight' => true,
                'offer_type' => 'sublease',
                'price_negotiable' => true,
                'environment' => 'urban',
            ],
            [
                'title' => 'Citylight - ul. Grabiszyńska / Grabiszyn',
                'type' => 'citylight',
                'location' => 'ul. Grabiszyńska 195',
                'city' => 'Wrocław',
                'region' => 'dolnoslaskie',
                'latitude' => 51.0894,
                'longitude' => 17.0021,
                'description' => "Panel na przystanku przy Grabiszyńskiej niedaleko cmentarza. Brzmi niepoważnie, ale tam naprawdę jest duży ruch — blisko centrum, dużo linii tramwajowych. Citylight jednostronny, podświetlany. Dobra lokalizacja dla usług lokalnych.",
                'price' => 700,
                'price_unit' => 'month',
                'width' => 1.20,
                'height' => 1.80,
                'variant' => 'single_sided',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['pedestrian'],
                'has_backlight' => true,
                'offer_type' => 'owner',
            ],
            [
                'title' => 'Siatka na ścianie - ul. Świdnicka / centrum',
                'type' => 'wall',
                'location' => 'ul. Świdnicka 12',
                'city' => 'Wrocław',
                'region' => 'dolnoslaskie',
                'latitude' => 51.1064,
                'longitude' => 17.0278,
                'description' => "Oferujemy wynajem powierzchni ściennej (siatka wielkoformatowa) na kamienicy przy ul. Świdnickiej we Wrocławiu. Ekspozycja 8x6m skierowana na ruch pieszy i samochodowy. Lokalizacja w obrębie centrum, wysoka intensywność ruchu pieszego. Właściciel nieruchomości prowadzi obsługę prawno-administracyjną. Cena netto, faktura VAT 23%. Preferowany wynajem kwartalny lub roczny — przy umowie rocznej rabat 15%. Kontakt w sprawie szczegółów technicznych i wizualizacji przez formularz.",
                'price' => 3200,
                'price_unit' => 'month',
                'width' => 8.00,
                'height' => 6.00,
                'traffic_intensity' => 'medium',
                'traffic_type' => ['pedestrian', 'car'],
                'has_backlight' => false,
                'lighting_type_banner' => 'none',
                'offer_type' => 'owner',
            ],

            // ══════════════════ POZNAŃ ══════════════════

            [
                'title' => 'Billboard - ul. Dąbrowskiego / Łazarz',
                'type' => 'billboard',
                'location' => 'ul. Dąbrowskiego 87',
                'city' => 'Poznań',
                'region' => 'wielkopolskie',
                'latitude' => 52.3921,
                'longitude' => 16.9012,
                'description' => "Billboard przy Dąbrowskiego na Łazarzu, jednostronny wychodzi na ulicę w kierunku centrum. Sporo tramwajów i aut, blisko UCK i kilku szkół. Sam stąd jestem i wiem że ruch jest tam zawsze. Oświetlony, dobry stan techniczny. Piszcie przez formularz.",
                'price' => 1700,
                'price_unit' => 'month',
                'width' => 5.04,
                'height' => 2.38,
                'variant' => 'standard',
                'road_class' => 'urban',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['car', 'pedestrian'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'environment' => 'urban',
            ],
            [
                'title' => 'Totem reklamowy - ul. Bukowska / Jeżyce',
                'type' => 'totem',
                'location' => 'ul. Bukowska 27',
                'city' => 'Poznań',
                'region' => 'wielkopolskie',
                'latitude' => 52.4098,
                'longitude' => 16.8912,
                'description' => "Pylon 1x3,5m przy Bukowskiej na Jeżycach, tuż przy wjeździe do centrum. Bardzo modna dzielnica, kawiarnie, sklepy — dobrze tu się pokazać jeśli kierujesz markę do aktywnych trzydziestolatków. Podświetlany, stan bdb. Dostępny od początku przyszłego miesiąca.",
                'price' => 1500,
                'price_unit' => 'month',
                'width' => 1.00,
                'height' => 3.50,
                'variant' => 'standard',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['pedestrian', 'car'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'price_negotiable' => true,
            ],

            // ══════════════════ GDAŃSK ══════════════════

            [
                'title' => 'Billboard - ul. Kartuska / Chełm',
                'type' => 'billboard',
                'location' => 'ul. Kartuska 245',
                'city' => 'Gdańsk',
                'region' => 'pomorskie',
                'latitude' => 54.3421,
                'longitude' => 18.5932,
                'description' => "Nośnik przy ul. Kartuskiej — drodze krajowej nr 7 w kierunku Kartuz. Lokalizacja przy stacji paliw i serwisie, co dodatkowo wydłuża ekspozycję dla zatrzymujących się kierowców. Szacowany DEC (Daily Effective Circulation): 14 000 pojazdów. Billboard jednostronny 6x3m z oświetleniem LED. Dedykowany branżom: motoryzacja, serwis, budownictwo, usługi lokalne. Zarządca nośnika: OutMedia Gdańsk. Umowa od 1 miesiąca, możliwa płatność kwartalna z rabatem.",
                'price' => 1900,
                'price_unit' => 'month',
                'width' => 6.00,
                'height' => 3.00,
                'variant' => 'standard',
                'road_class' => 'national',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['car'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'environment' => 'suburban',
            ],
            [
                'title' => 'Citylight - przystanek Łostowice Świętokrzyska',
                'type' => 'citylight',
                'location' => 'ul. Łostowicka 93',
                'city' => 'Gdańsk',
                'region' => 'pomorskie',
                'latitude' => 54.3312,
                'longitude' => 18.5821,
                'description' => "Panel na przystanku na Łostowicach — duże osiedle, mnóstwo rodzin i pracujących. Autobusy kursują często, więc przy przystanku zawsze ktoś stoi. Podświetlany, format standardowy. Fajne miejsce pod sklepy spożywcze, siłownie, usługi dla mieszkańców.",
                'price' => 650,
                'price_unit' => 'month',
                'width' => 1.20,
                'height' => 1.80,
                'variant' => 'single_sided',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['pedestrian'],
                'has_backlight' => true,
                'offer_type' => 'owner',
            ],
            [
                'title' => 'Baner na ogrodzeniu - Port Gdański / Nowy Port',
                'type' => 'banner',
                'location' => 'ul. Majowa 2',
                'city' => 'Gdańsk',
                'region' => 'pomorskie',
                'latitude' => 54.3891,
                'longitude' => 18.6612,
                'description' => "Przestrzeń banerowa na ogrodzeniu przy ul. Majowej w Nowym Porcie — strefa przemysłowo-portowa Gdańska. Format do 12x2m, mocowanie do istniejącej konstrukcji. Ruch docelowy: pojazdy ciężarowe, pracownicy portu, transport lokalny. Ekspozycja dzienna. Idealne zastosowanie: branża logistyczna, spedycja, wynajem maszyn, usługi B2B. Warunki: wynajem miesięczny lub kwartalny, montaż i demontaż grafiki we własnym zakresie lub na zlecenie (wycena na zapytanie).",
                'price' => 900,
                'price_unit' => 'month',
                'width' => 12.00,
                'height' => 2.00,
                'traffic_intensity' => 'medium',
                'traffic_type' => ['car'],
                'has_backlight' => false,
                'lighting_type_banner' => 'none',
                'offer_type' => 'owner',
                'price_negotiable' => true,
            ],

            // ══════════════════ ŁÓDŹ ══════════════════

            [
                'title' => 'Billboard - ul. Brzezińska / Widzew',
                'type' => 'billboard',
                'location' => 'ul. Brzezińska 37',
                'city' => 'Łódź',
                'region' => 'lodzkie',
                'latitude' => 51.7712,
                'longitude' => 19.5034,
                'description' => "Billboard przy Brzezińskiej na Widzewie — ulica jest mocno zakorkowana wieczorami bo to główny dojazd ze wschodnich części Łodzi. Jednostronny, oświetlony, standard 504x238. Mam możliwość wymiany grafiki co miesiąc, sam organizuję druk za dodatkową opłatą jeśli potrzeba.",
                'price' => 1100,
                'price_unit' => 'month',
                'width' => 5.04,
                'height' => 2.38,
                'variant' => 'standard',
                'road_class' => 'urban',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['car'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'price_negotiable' => true,
                'environment' => 'urban',
            ],

            // ══════════════════ KATOWICE ══════════════════

            [
                'title' => 'Billboard - ul. Murckowska / Muchowiec',
                'type' => 'billboard',
                'location' => 'ul. Murckowska 14',
                'city' => 'Katowice',
                'region' => 'slaskie',
                'latitude' => 50.2398,
                'longitude' => 19.0412,
                'description' => "Nośnik reklamowy przy ul. Murckowskiej w Katowicach, w pobliżu kompleksu sportowo-rekreacyjnego Muchowiec. Lokalizacja obsługuje ruch z osiedli południa Katowic w kierunku drogi S86 i DTŚ. Szacowane dzienne przejazdy: 9 000–12 000 pojazdów. Billboard jednostronny 5,04x2,38m, podświetlany LED. Zarządca: Śląska Agencja Mediów Zewnętrznych. Minimalna umowa 3 miesiące, faktura VAT, możliwość pomocy przy organizacji druku.",
                'price' => 1600,
                'price_unit' => 'month',
                'width' => 5.04,
                'height' => 2.38,
                'variant' => 'standard',
                'road_class' => 'urban',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['car'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'environment' => 'suburban',
            ],
            [
                'title' => 'Citylight - przystanek Rolna / Koszutka',
                'type' => 'citylight',
                'location' => 'ul. Rolna 43',
                'city' => 'Katowice',
                'region' => 'slaskie',
                'latitude' => 50.2589,
                'longitude' => 19.0078,
                'description' => "Panel citylight przy przystanku tramwajowym na Rolnej, dzielnica Koszutka. Sporo pracujących ludzi wsiada tam rano, blisko kilku osiedli. Podświetlany, dostępny od zaraz. Dobra lokalizacja dla aptek, sklepów spożywczych, usług zdrowotnych.",
                'price' => 680,
                'price_unit' => 'month',
                'width' => 1.20,
                'height' => 1.80,
                'variant' => 'single_sided',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['pedestrian'],
                'has_backlight' => true,
                'offer_type' => 'owner',
            ],

            // ══════════════════ SZCZECIN ══════════════════

            [
                'title' => 'Billboard - ul. Struga / Niebuszewo',
                'type' => 'billboard',
                'location' => 'ul. Andrzeja Struga 15',
                'city' => 'Szczecin',
                'region' => 'zachodniopomorskie',
                'latitude' => 53.4312,
                'longitude' => 14.5678,
                'description' => "Billboard przy ul. Struga na Niebuszewie. Spokojniejsza dzielnica ale tranzyt stąd do centrum jest spory. Jednostronny, stan dobry, oświetlenie działa. Właśnie skończyła się umowa poprzedniego klienta więc jest od razu dostępny. Wolę kontakt przez wiadomość.",
                'price' => 1200,
                'price_unit' => 'month',
                'width' => 5.04,
                'height' => 2.38,
                'variant' => 'standard',
                'road_class' => 'urban',
                'traffic_intensity' => 'low',
                'traffic_type' => ['car'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'price_negotiable' => true,
                'environment' => 'urban',
            ],

            // ══════════════════ LUBLIN ══════════════════

            [
                'title' => 'Billboard - ul. Kraśnicka / Czuby',
                'type' => 'billboard',
                'location' => 'ul. Kraśnicka 178',
                'city' => 'Lublin',
                'region' => 'lubelskie',
                'latitude' => 51.2165,
                'longitude' => 22.5012,
                'description' => "Mam billboard przy Kraśnickiej na wylocie z Lublina w stronę Kraśnika. Droga bardzo ruchliwa — dużo busów i tirów, bo to ważny tranzyt na południe. Nośnik jednostronny, skierowany na wyjazd z miasta. Oświetlony, cena za miesiąc, przy dłuższej umowie jest pole do rozmowy.",
                'price' => 1350,
                'price_unit' => 'month',
                'width' => 5.04,
                'height' => 2.38,
                'variant' => 'standard',
                'road_class' => 'national',
                'traffic_intensity' => 'high',
                'traffic_type' => ['car'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'price_negotiable' => true,
                'environment' => 'suburban',
            ],
            [
                'title' => 'Totem reklamowy - ul. Zana / Czuby Północne',
                'type' => 'totem',
                'location' => 'ul. Tomasza Zana 38',
                'city' => 'Lublin',
                'region' => 'lubelskie',
                'latitude' => 51.2298,
                'longitude' => 22.5234,
                'description' => "Pylon dwustronny przy ul. Zana, między galerią Atrium a osiedlem Czuby Północne. Duże osiedle, mnóstwo mieszkańców, blisko galeria i kilka sklepów. Dobra ekspozycja dla usług lokalnych — przychodnia, restauracja, sklep. Podświetlany LED, format 1,2x3m. Dostępny od zaraz.",
                'price' => 1100,
                'price_unit' => 'month',
                'width' => 1.20,
                'height' => 3.00,
                'variant' => 'double_sided',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['pedestrian', 'car'],
                'has_backlight' => true,
                'offer_type' => 'owner',
            ],

            // ══════════════════ BYDGOSZCZ ══════════════════

            [
                'title' => 'Reklama w transporcie - autobusy MZK Bydgoszcz',
                'type' => 'transport',
                'location' => 'ul. Inowrocławska 11',
                'city' => 'Bydgoszcz',
                'region' => 'kujawsko-pomorskie',
                'latitude' => 53.1235,
                'longitude' => 18.0234,
                'description' => "Agencja MediaBus oferuje powierzchnię reklamową na taborze komunikacji miejskiej w Bydgoszczy. Dostępne formaty: tylna szyba (100x70cm), boki nadwozia (700x100cm), naklejki wewnętrzne. Flota obejmuje 80 autobusów obsługujących wszystkie dzielnice miasta. Minimalny czas kampanii: 4 tygodnie. Możliwość targetowania wybranych linii lub całej floty. Wycena indywidualna — proszę o kontakt z podaniem pożądanego formatu i okresu kampanii.",
                'price' => 2400,
                'price_unit' => 'month',
                'width' => 7.00,
                'height' => 1.00,
                'traffic_intensity' => 'high',
                'traffic_type' => ['car', 'pedestrian'],
                'has_backlight' => false,
                'offer_type' => 'agency',
                'transport_scope' => 'city',
                'vehicle_count' => 80,
            ],

            // ══════════════════ RZESZÓW ══════════════════

            [
                'title' => 'Billboard - al. Rejtana / centrum Rzeszowa',
                'type' => 'billboard',
                'location' => 'al. Leopolda Lisa-Kuli 19',
                'city' => 'Rzeszów',
                'region' => 'podkarpackie',
                'latitude' => 50.0412,
                'longitude' => 22.0023,
                'description' => "Billboard przy głównej alei w centrum Rzeszowa, niedaleko dworca. Rzeszów szybko rośnie i ruch w centrum jest coraz większy. Nośnik dwustronny, widoczny zarówno od strony ronda jak i w kierunku galerii. Sam mam kilka nośników w mieście — ten jest najlepiej zlokalizowany z całej mojej oferty. Cena miesięczna, możliwa faktura.",
                'price' => 2100,
                'price_unit' => 'month',
                'width' => 6.00,
                'height' => 3.00,
                'variant' => 'two_sided',
                'road_class' => 'urban',
                'traffic_intensity' => 'high',
                'traffic_type' => ['car', 'pedestrian'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'has_vat_invoice' => true,
                'environment' => 'urban',
            ],

            // ══════════════════ OKOLICE WARSZAWY ══════════════════

            [
                'title' => 'Billboard - ul. Puławska / Piaseczno',
                'type' => 'billboard',
                'location' => 'ul. Puławska 34',
                'city' => 'Piaseczno',
                'region' => 'mazowieckie',
                'latitude' => 52.0823,
                'longitude' => 21.0167,
                'description' => "Nośnik przy Puławskiej w Piasecznie, kilkaset metrów za granicą Warszawy. Jeden z głównych wyjazdów z południa aglomeracji — korki tu stoją codziennie rano i wieczorem, więc czas ekspozycji jest naprawdę długi. Jednostronny 6x3m, oświetlony. Poprzedni najemca miał salon samochodowy — polecam ten typ branży.",
                'price' => 1800,
                'price_unit' => 'month',
                'width' => 6.00,
                'height' => 3.00,
                'variant' => 'standard',
                'road_class' => 'national',
                'traffic_intensity' => 'high',
                'traffic_type' => ['car'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'price_negotiable' => true,
                'environment' => 'suburban',
            ],
            [
                'title' => 'Citylight - przystanek PKP Pruszków',
                'type' => 'citylight',
                'location' => 'ul. Bohaterów Warszawy 2',
                'city' => 'Pruszków',
                'region' => 'mazowieckie',
                'latitude' => 52.1689,
                'longitude' => 20.8012,
                'description' => "Panel reklamowy przy wejściu na stację PKP Pruszków. Codziennie kilka tysięcy dojeżdżających do Warszawy — większość to osoby w wieku 25–50 lat, pracujące. Ekspozycja bardzo dobra bo ludzie stoją i czekają na peron. Format 120x180cm, podświetlany, stan bdb. Dostępny od następnego miesiąca.",
                'price' => 780,
                'price_unit' => 'month',
                'width' => 1.20,
                'height' => 1.80,
                'variant' => 'single_sided',
                'traffic_intensity' => 'high',
                'traffic_type' => ['pedestrian'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'daily_passengers' => 4200,
            ],

            // ══════════════════ DROGI KRAJOWE / EKSPRESOWE ══════════════════

            [
                'title' => 'Billboard - DK7 / Białobrzegi (wjazd od Radomia)',
                'type' => 'billboard',
                'location' => 'ul. Warszawska 112',
                'city' => 'Białobrzegi',
                'region' => 'mazowieckie',
                'latitude' => 51.6589,
                'longitude' => 20.9456,
                'description' => "Billboard przy drodze krajowej nr 7 między Radomiem a Warszawą, miejscowość Białobrzegi. Trasa bardzo uczęszczana — jedyna prosta droga z południa Mazowsza do stolicy. Nośnik jednostronny skierowany na Warszawę, widoczny z daleka bo teren otwarty. Idealne dla firm z branży transportowej, budowlanej albo deweloperów z okolic Radomia. Cena negocjowalna przy umowie minimum 3 miesiące.",
                'price' => 1450,
                'price_unit' => 'month',
                'width' => 6.00,
                'height' => 3.00,
                'variant' => 'standard',
                'road_class' => 'national',
                'traffic_intensity' => 'high',
                'traffic_type' => ['car'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'price_negotiable' => true,
                'environment' => 'rural',
            ],
            [
                'title' => 'Billboard - S8 okolice Mszczonowa (kierunek Warszawa)',
                'type' => 'billboard',
                'location' => 'Mszczonów, MOP Adamowice',
                'city' => 'Mszczonów',
                'region' => 'mazowieckie',
                'latitude' => 51.9712,
                'longitude' => 20.5234,
                'description' => "Nośnik reklamowy zlokalizowany przy MOP Adamowice na drodze ekspresowej S8, 45 km od Warszawy. Pozycja przy miejscu obsługi podróżnych gwarantuje zatrzymujący się ruch i dłuższy czas kontaktu z nośnikiem. Szacowany dobowy ruch: 18 000–22 000 pojazdów. Format 6x3m, oświetlenie LED, nośnik dwustronny. Zarządca: OutPost Media Sp. z o.o. Umowa od 3 miesięcy, faktury VAT, media kit na zapytanie.",
                'price' => 3200,
                'price_unit' => 'month',
                'width' => 6.00,
                'height' => 3.00,
                'variant' => 'two_sided',
                'road_class' => 'express',
                'traffic_intensity' => 'high',
                'traffic_type' => ['car'],
                'has_backlight' => true,
                'offer_type' => 'agency',
                'environment' => 'rural',
                'estimated_daily_views' => 20000,
            ],
            [
                'title' => 'Billboard - DK1 / Piotrków Trybunalski Południe',
                'type' => 'billboard',
                'location' => 'ul. Sulejowska 201',
                'city' => 'Piotrków Trybunalski',
                'region' => 'lodzkie',
                'latitude' => 51.3789,
                'longitude' => 19.7023,
                'description' => "Stary, sprawdzony nośnik przy DK1 za Piotrkowem jadąc na południe. Trasa na Częstochowę i Śląsk, zawsze spory ruch — szczególnie TIRy i busy. Billboard jednostronny, skierowany na kierowców jadących na południe. Oświetlony. Mam go już od 8 lat i zawsze był wynajęty — dopiero teraz jest wolny po poprzednim kliencie.",
                'price' => 1250,
                'price_unit' => 'month',
                'width' => 5.04,
                'height' => 2.38,
                'variant' => 'standard',
                'road_class' => 'national',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['car'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'price_negotiable' => true,
                'environment' => 'suburban',
            ],

            // ══════════════════ MNIEJSZE MIASTA ══════════════════

            [
                'title' => 'Ekran LED - ul. Kościuszki / Kielce centrum',
                'type' => 'led_screen',
                'location' => 'ul. Tadeusza Kościuszki 8',
                'city' => 'Kielce',
                'region' => 'swietokrzyskie',
                'latitude' => 50.8661,
                'longitude' => 20.6331,
                'description' => "Ekran LED w ścisłym centrum Kielc, przy głównej ulicy handlowej. Lokalizacja przy przejściu dla pieszych z długim cyklem świetlnym — idealna ekspozycja dla pieszych i zatrzymanych kierowców. Rozdzielczość Full HD, jasność 6000 nitów, praca 24/7. Sprzedajemy czas emisji w blokach tygodniowych (min. 2 tygodnie) lub miesięcznych. Cena za emisję w rotacji — wyłączność do uzgodnienia.",
                'price' => 2200,
                'price_unit' => 'month',
                'width' => 3.00,
                'height' => 2.00,
                'resolution' => '1920x1080',
                'pixel_pitch' => '8',
                'brightness' => '6000',
                'ambient_light_control' => true,
                'traffic_intensity' => 'medium',
                'traffic_type' => ['pedestrian', 'car'],
                'has_backlight' => true,
                'offer_type' => 'agency',
                'variant' => 'standard',
                'environment' => 'urban',
            ],
            [
                'title' => 'Baner na ogrodzeniu - Tarnów, ul. Krakowska',
                'type' => 'banner',
                'location' => 'ul. Krakowska 153',
                'city' => 'Tarnów',
                'region' => 'malopolskie',
                'latitude' => 50.0134,
                'longitude' => 20.9723,
                'description' => "Mam ogrodzenie przy swojej działce przy Krakowskiej w Tarnowie i mogę je udostępnić pod baner. Działka stoi przy wjeździe do miasta od strony Krakowa — sporo aut tamtędy jedzie zwłaszcza przez wakacje i weekendy. Miejsce na baner mniej więcej 8x2m, mogę przygotować punkty montażowe. Cena do negocjacji, wolę dłuższy wynajem.",
                'price' => 600,
                'price_unit' => 'month',
                'width' => 8.00,
                'height' => 2.00,
                'traffic_intensity' => 'medium',
                'traffic_type' => ['car'],
                'has_backlight' => false,
                'lighting_type_banner' => 'none',
                'offer_type' => 'owner',
                'price_negotiable' => true,
                'environment' => 'suburban',
            ],
            [
                'title' => 'Citylight - przystanek Olsztyn / Centrum',
                'type' => 'citylight',
                'location' => 'al. Piłsudskiego 38',
                'city' => 'Olsztyn',
                'region' => 'warminsko-mazurskie',
                'latitude' => 53.7784,
                'longitude' => 20.4801,
                'description' => "Panel reklamowy na przystanku tramwajowym przy alei Piłsudskiego — główna arteria Olsztyna. Przystanek obsługuje kilka linii, duży ruch pasażerski cały dzień. Podświetlany, format 120x180, stan bardzo dobry. Dobra lokalizacja dla firm chcących zaistnieć w Olsztynie — miasto dynamicznie się rozwija, sporo nowych mieszkańców.",
                'price' => 620,
                'price_unit' => 'month',
                'width' => 1.20,
                'height' => 1.80,
                'variant' => 'single_sided',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['pedestrian'],
                'has_backlight' => true,
                'offer_type' => 'owner',
            ],
            [
                'title' => 'Reklama na taksówce - Warszawa, własny samochód',
                'type' => 'mobile',
                'location' => 'Warszawa',
                'city' => 'Warszawa',
                'region' => 'mazowieckie',
                'latitude' => 52.2297,
                'longitude' => 21.0122,
                'description' => "Jeżdżę taksówką po Warszawie od 6 lat, głównie Śródmieście, Mokotów, Wola, czasem Ursynów i Wilanów. Pracuję codziennie ok. 10-12 godzin. Mam miejsce na naklejkę z tyłu auta i mogę wozić ulotki w środku dla pasażerów. Tanio, ale skutecznie — każdy pasażer siedzi i patrzy. Kontakt przez wiadomość.",
                'price' => 200,
                'price_unit' => 'month',
                'width' => 0.60,
                'height' => 0.30,
                'traffic_intensity' => 'high',
                'traffic_type' => ['car', 'pedestrian'],
                'has_backlight' => false,
                'offer_type' => 'owner',
                'mobile_exposure_mode' => 'moving',
                'route_area' => 'Warszawa — Śródmieście, Mokotów, Wola',
                'vehicle_count' => 1,
                'operating_hours' => '07:00-19:00',
                'price_negotiable' => true,
            ],
            [
                'title' => 'Billboard - ul. Legnicka / Lubin (wjazd od autostrady)',
                'type' => 'billboard',
                'location' => 'ul. Legnicka 84',
                'city' => 'Lubin',
                'region' => 'dolnoslaskie',
                'latitude' => 51.4023,
                'longitude' => 16.2134,
                'description' => "Billboard przy drodze z autostrady A4 do Lubina. Lubin to miasto KGHM — dużo firm dostawczych, pracowników i kontrahentów tamtędy jeździ. Nośnik jednostronny skierowany na wjazd do miasta. Stan dobry, oświetlony. Cena miesięczna, wystawiam fakturę.",
                'price' => 1050,
                'price_unit' => 'month',
                'width' => 5.04,
                'height' => 2.38,
                'variant' => 'standard',
                'road_class' => 'urban',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['car'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'has_vat_invoice' => true,
                'environment' => 'suburban',
            ],
            [
                'title' => 'Siatka wielkoformatowa - kamienica Wieliczka Rynek',
                'type' => 'wall',
                'location' => 'Rynek 15',
                'city' => 'Wieliczka',
                'region' => 'malopolskie',
                'latitude' => 49.9878,
                'longitude' => 20.0645,
                'description' => "Ściana reklamowa na kamienicy przy Rynku w Wieliczce — kilkaset metrów od wejścia do Kopalni Soli. Przez Wieliczkę przejeżdżają setki tysięcy turystów rocznie. Powierzchnia 6x4m, boczna elewacja widoczna z Rynku. Polecam firmom turystycznym, restauracjom, hotelom z okolic Krakowa. Minimum 3 miesiące, możliwa umowa sezonowa.",
                'price' => 2800,
                'price_unit' => 'month',
                'width' => 6.00,
                'height' => 4.00,
                'traffic_intensity' => 'high',
                'traffic_type' => ['pedestrian', 'car'],
                'has_backlight' => false,
                'lighting_type_banner' => 'none',
                'offer_type' => 'owner',
                'price_negotiable' => true,
                'environment' => 'urban',
            ],

        ];

        $defaults = [
            'owner_email'             => 'test@test.pl',
            'phone'                   => '',
            'contact_preference'      => 'email',
            'is_active'               => true,
            'is_verified'             => true,
            'has_image'               => false,
            'images'                  => [],
            'has_vat_invoice'         => true,
            'price_includes_print'    => false,
            'price_includes_mounting' => false,
            'price_negotiable'        => false,
            'status'                  => 'active',
        ];

        // Daty dodania — wszystkie w kwietniu 2026
        $createdDates = [
            Carbon::create(2026, 4, 1, 9, 12),
            Carbon::create(2026, 4, 1, 14, 33),
            Carbon::create(2026, 4, 2, 8, 55),
            Carbon::create(2026, 4, 2, 17, 21),
            Carbon::create(2026, 4, 3, 10, 44),
            Carbon::create(2026, 4, 3, 13, 07),
            Carbon::create(2026, 4, 4, 9, 30),
            Carbon::create(2026, 4, 4, 16, 18),
            Carbon::create(2026, 4, 5, 11, 52),
            Carbon::create(2026, 4, 6, 8, 40),
            Carbon::create(2026, 4, 6, 15, 29),
            Carbon::create(2026, 4, 7, 10, 15),
            Carbon::create(2026, 4, 7, 18, 03),
            Carbon::create(2026, 4, 8, 9, 47),
            Carbon::create(2026, 4, 8, 14, 22),
            Carbon::create(2026, 4, 9, 11, 38),
            Carbon::create(2026, 4, 9, 16, 55),
            Carbon::create(2026, 4, 10, 8, 20),
            Carbon::create(2026, 4, 10, 13, 44),
            Carbon::create(2026, 4, 11, 9, 58),
            Carbon::create(2026, 4, 11, 17, 31),
            Carbon::create(2026, 4, 12, 10, 06),
            Carbon::create(2026, 4, 12, 15, 48),
            Carbon::create(2026, 4, 13, 9, 12),
            Carbon::create(2026, 4, 13, 14, 37),
            Carbon::create(2026, 4, 13, 19, 02),
            Carbon::create(2026, 4, 14, 8, 33),
            Carbon::create(2026, 4, 14, 10, 19),
            Carbon::create(2026, 4, 14, 11, 45),
            Carbon::create(2026, 4, 14, 12, 28),
            Carbon::create(2026, 4, 14, 13, 55),
            Carbon::create(2026, 4, 14, 14, 41),
            Carbon::create(2026, 4, 14, 15, 17),
            Carbon::create(2026, 4, 14, 16, 03),
            Carbon::create(2026, 4, 14, 17, 22),
        ];

        foreach ($ads as $index => $ad) {
            $data = array_merge($defaults, $ad);

            if (isset($data['width'], $data['height'])) {
                $data['orientation'] = $data['width'] >= $data['height'] ? 'horizontal' : 'vertical';
            }

            $data['slug'] = Str::slug($data['title']);

            // Przypisz datę dodania
            $createdAt = $createdDates[$index] ?? now()->subDays(rand(1, 30));

            // Kilka ogłoszeń jako dostępne od przyszłej daty
            if (in_array($index, [2, 7, 12, 17])) {
                $data['available_from'] = now()->addDays(rand(10, 25));
            }

            $ad = Advertisement::updateOrCreate(
                ['slug' => $data['slug']],
                $data
            );

            // Ustaw datę created_at ręcznie (poza fillable)
            $ad->timestamps = false;
            $ad->created_at = $createdAt;
            $ad->updated_at = $createdAt;
            $ad->save();
            $ad->timestamps = true;
        }

        $this->command->info('Dodano ' . count($ads) . ' ogłoszeń. Email zarządzania: test@test.pl');
    }
}
