<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use App\Models\Advertisement;
use Illuminate\Support\Str;

class AdvertisementsSeeder extends Seeder
{
    /**
     * Startowe ogłoszenia platformy.
     * Email zarządzania: test@test.pl
     * Zdjęcia dodaj ręcznie przez panel /zarzadzaj
     */
    public function run(): void
    {
        $ads = [

            // ══════════════════ WARSZAWA ══════════════════

            [
                'title' => 'Billboard przy Modlińskiej - Białołęka, wyjazd z Warszawy',
                'type' => 'billboard',
                'location' => 'ul. Modlińska 223',
                'city' => 'Warszawa',
                'region' => 'mazowieckie',
                'latitude' => 52.3156,
                'longitude' => 20.9887,
                'description' => "Mam wolny billboard przy Modlińskiej na Białołęce, wyjazd w stronę Nieporętu. Dużo aut rano i po południu, bo ludzie dojeżdżają z tamtych okolic do pracy. Sam mieszkam niedaleko i powiem szczerze - każdy kto jedzie tą drogą mija ten baner. Minimalny wynajem miesiąc, cena do ustalenia przy dłuższej umowie. Kontakt przez formularz.",
                'price' => 1400,
                'price_unit' => 'month',
                'width' => 5.04,
                'height' => 2.38,
                'variant' => 'standard',
                'road_class' => 'urban',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['vehicular'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'price_negotiable' => true,
            ],
            [
                'title' => 'Ekran LED Targówek - skrzyżowanie ze świetlną',
                'type' => 'led_screen',
                'location' => 'ul. Głębocka 13',
                'city' => 'Warszawa',
                'region' => 'mazowieckie',
                'latitude' => 52.2872,
                'longitude' => 21.0743,
                'description' => "Oferujemy czas antenowy na ekranie LED przy ul. Głębockiej na Targówku. Nośnik zlokalizowany przy skrzyżowaniu z długim cyklem sygnalizacji świetlnej, co przekłada się na ponadprzeciętny dwell time dla kierowców. Parametry: rozdzielczość Full HD, automatyczna regulacja jasności, praca 24/7. Dostępne pakiety: wyłączność dobowa, emisja w rotacji (do 6 klientów). Minimalna długość kampanii: 2 tygodnie. Zapraszamy do przesłania zapytania.",
                'price' => 3200,
                'price_unit' => 'month',
                'width' => 6.00,
                'height' => 3.00,
                'resolution' => '1920x1080',
                'pixel_pitch' => 8,
                'brightness' => 6000,
                'ambient_light_control' => true,
                'traffic_intensity' => 'medium',
                'traffic_type' => ['vehicular', 'pedestrian'],
                'has_backlight' => true,
                'offer_type' => 'agency',
                'variant' => 'standard',
            ],
            [
                'title' => 'Citylight Bródno - ruchliwy przystanek kilku linii',
                'type' => 'citylight',
                'location' => 'ul. Kondratowicza 37',
                'city' => 'Warszawa',
                'region' => 'mazowieckie',
                'latitude' => 52.2803,
                'longitude' => 21.0612,
                'description' => "Panel na przystanku Kondratowicza na Bródnie - staje tu 11 i 25 tramwaj plus kilka autobusów, między innymi 156 i 203. Rano jest tu kolejka bo tramwaje jeżdżą co kilkanaście minut i ludzie czekają. Podświetlany, format 120x180. Jedna uwaga: grafika trochę pogięta na lewym rogu po poprzednim najemcy, ale można wymienić - cena z wymianą do dogadania.",
                'price' => 850,
                'price_unit' => 'month',
                'width' => 1.20,
                'height' => 1.80,
                'variant' => 'single_sided',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['pedestrian'],
                'has_backlight' => true,
                'offer_type' => 'owner',
            ],
            [
                'title' => 'Billboard wylot z Warszawy na Marki i Legionowo',
                'type' => 'billboard',
                'location' => 'ul. Płochocińska 85',
                'city' => 'Warszawa',
                'region' => 'mazowieckie',
                'latitude' => 52.3089,
                'longitude' => 21.0534,
                'description' => "Billboard przy wyjeździe z Warszawy w stronę Marek i Legionowa - ulica Płochocińska. Sporo aut wcześnie rano i późnym popołudniem. Jednostronny, format 504x238 cm, oświetlony. Dobry na lokalną firmę albo dewelopera z tamtych okolic. Piszcie na formularz.",
                'price' => 1100,
                'price_unit' => 'month',
                'width' => 5.04,
                'height' => 2.38,
                'variant' => 'standard',
                'road_class' => 'urban',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['vehicular'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'price_negotiable' => true,
            ],

            // ══════════════════ KRAKÓW ══════════════════

            [
                'title' => 'Wolny billboard Nowa Huta Kraków',
                'type' => 'billboard',
                'location' => 'ul. Półkole 18',
                'city' => 'Kraków',
                'region' => 'malopolskie',
                'latitude' => 50.0769,
                'longitude' => 20.0521,
                'description' => "Wstawiłem billboard przy Półkolu w Nowej Hucie jakieś 2 lata temu i teraz go udostępniam. Dużo aut tamtędy jedzie bo to dojazd z osiedli do centrum i do obwodnicy. Oświetlony od zachodu słońca, stan dobry. Odezwijcie się przez wiadomość to dogadamy szczegóły.",
                'price' => 1300,
                'price_unit' => 'month',
                'width' => 5.04,
                'height' => 2.38,
                'variant' => 'standard',
                'road_class' => 'urban',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['vehicular'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'price_negotiable' => true,
            ],
            [
                'title' => 'Citylight na przystanku os. Piastów Kraków',
                'type' => 'citylight',
                'location' => 'os. Piastów 52',
                'city' => 'Kraków',
                'region' => 'malopolskie',
                'latitude' => 50.0812,
                'longitude' => 20.0253,
                'description' => "Piastów, Nowa Huta - przystanek obsługiwany przez 22 tramwaj w kierunku centrum i kilka autobusów osiedlowych. Rankiem wsiada tu dużo robotników z kombinatu i pobliskich zakładów. Jeden minus, który powiem wprost: zimą wiata bywa zasypana i panel trochę mniej widoczny od ulicy. Latem jest bez zarzutu. Cena za miesiąc z wliczonym utrzymaniem, przy dłuższej umowie gadamy.",
                'price' => 750,
                'price_unit' => 'month',
                'width' => 1.20,
                'height' => 1.80,
                'variant' => 'single_sided',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['pedestrian'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'price_negotiable' => true,
            ],
            [
                'title' => 'Wynajem czasu emisji ekran LED - Podgórze Kraków',
                'type' => 'led_screen',
                'location' => 'ul. Kamieńskiego 11',
                'city' => 'Kraków',
                'region' => 'malopolskie',
                'latitude' => 50.0284,
                'longitude' => 19.9623,
                'description' => "Agencja AdPoint udostępnia powierzchnię na ekranie DOOH przy ul. Kamieńskiego w Krakowie-Podgórzu. Lokalizacja przy węźle tramwajowym, szacowany dzienny OTS: 8 000–11 000 osób. Profil odbiorcy: mieszkańcy rozwijającej się dzielnicy, pracownicy pobliskich biur i usług. Ekran pracuje całą dobę z automatyczną optymalizacją jasności. Możliwość zakupu emisji w modelu tygodniowym lub miesięcznym. Szczegółowa oferta i media kit dostępne po kontakcie.",
                'price' => 2800,
                'price_unit' => 'month',
                'width' => 4.00,
                'height' => 2.50,
                'resolution' => '1280x720',
                'pixel_pitch' => 10,
                'ambient_light_control' => true,
                'traffic_intensity' => 'medium',
                'traffic_type' => ['vehicular', 'pedestrian'],
                'has_backlight' => true,
                'offer_type' => 'agency',
                'variant' => 'standard',
            ],

            // ══════════════════ WROCŁAW ══════════════════

            [
                'title' => 'Billboard dwustronny przy obwodnicy - Wrocław Fabryczna',
                'type' => 'billboard',
                'location' => 'ul. Kosmonautów 51',
                'city' => 'Wrocław',
                'region' => 'dolnoslaskie',
                'latitude' => 51.0989,
                'longitude' => 16.9823,
                'description' => "Powierzchnia reklamowa przy ul. Kosmonautów we Wrocławiu, w bezpośrednim sąsiedztwie wjazdu na obwodnicę i trasę do autostrady A4. Nośnik dwustronny 6x3m skierowany na ruch w obu kierunkach - centrum oraz węzeł autostradowy. Profil ruchu: mieszany (osobowy, dostawczy, ciężarowy). Oświetlenie LED, ekspozycja całodobowa. Nośnik zarządzany przez Grupę Reklam Zewnętrznych Południe Sp. z o.o. Minimalna umowa: 1 miesiąc. Faktura VAT.",
                'price' => 2600,
                'price_unit' => 'month',
                'width' => 6.00,
                'height' => 3.00,
                'variant' => 'two_sided',
                'road_class' => 'urban',
                'traffic_intensity' => 'high',
                'traffic_type' => ['vehicular'],
                'has_backlight' => true,
                'offer_type' => 'sublease',
                'price_negotiable' => true,
            ],
            [
                'title' => 'Panel citylight Grabiszyńska Wrocław',
                'type' => 'citylight',
                'location' => 'ul. Grabiszyńska 195',
                'city' => 'Wrocław',
                'region' => 'dolnoslaskie',
                'latitude' => 51.0894,
                'longitude' => 17.0021,
                'description' => "Panel na przystanku przy Grabiszyńskiej niedaleko cmentarza. Brzmi niepoważnie, ale tam naprawdę jest duży ruch - blisko centrum, dużo linii tramwajowych. Citylight jednostronny, podświetlany. Dobra lokalizacja dla usług lokalnych.",
                'price' => 700,
                'price_unit' => 'month',
                'width' => 1.20,
                'height' => 1.80,
                'variant' => 'single_sided',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['pedestrian'],
                'has_backlight' => true,
                'offer_type' => 'owner',
            ],
            [
                'title' => 'Ściana pod siatę wielkoformatową - centrum Wrocławia',
                'type' => 'wall',
                'location' => 'ul. Świdnicka 12',
                'city' => 'Wrocław',
                'region' => 'dolnoslaskie',
                'latitude' => 51.1064,
                'longitude' => 17.0278,
                'description' => "Ściana boczna kamienicy przy Świdnickiej, centrum Wrocławia. 8x6m, widoczna z ulicy. Preferuję wynajem na minimum kwartał. Kontakt przez formularz.",
                'price' => 3200,
                'price_unit' => 'month',
                'width' => 8.00,
                'height' => 6.00,
                'traffic_intensity' => 'medium',
                'traffic_type' => ['pedestrian', 'vehicular'],
                'has_backlight' => false,
                'lighting_type_banner' => 'none',
                'offer_type' => 'owner',
            ],

            // ══════════════════ POZNAŃ ══════════════════

            [
                'title' => 'Billboard Łazarz Poznań blisko UCK',
                'type' => 'billboard',
                'location' => 'ul. Dąbrowskiego 87',
                'city' => 'Poznań',
                'region' => 'wielkopolskie',
                'latitude' => 52.3921,
                'longitude' => 16.9012,
                'description' => "Billboard przy Dąbrowskiego na Łazarzu, jednostronny wychodzi na ulicę w kierunku centrum. Sporo tramwajów i aut, blisko UCK i kilku szkół. Sam stąd jestem i wiem że ruch jest tam zawsze. Oświetlony, dobry stan techniczny. Piszcie przez formularz.",
                'price' => 1700,
                'price_unit' => 'month',
                'width' => 5.04,
                'height' => 2.38,
                'variant' => 'standard',
                'road_class' => 'urban',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['vehicular', 'pedestrian'],
                'has_backlight' => true,
                'offer_type' => 'owner',
            ],
            [
                'title' => 'Pylon przy wjeździe do centrum - ul. Bukowska, Jeżyce Poznań',
                'type' => 'totem',
                'location' => 'ul. Bukowska 27',
                'city' => 'Poznań',
                'region' => 'wielkopolskie',
                'latitude' => 52.4098,
                'longitude' => 16.8912,
                'description' => "Pylon 1x3,5m przy Bukowskiej na Jeżycach, tuż przy wjeździe do centrum. Bardzo modna dzielnica, kawiarnie, sklepy - dobrze tu się pokazać jeśli kierujesz markę do aktywnych trzydziestolatków. Podświetlany, stan bdb. Dostępny od początku przyszłego miesiąca.",
                'price' => 1500,
                'price_unit' => 'month',
                'width' => 1.00,
                'height' => 3.50,
                'variant' => 'pylon',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['pedestrian', 'vehicular'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'price_negotiable' => true,
            ],

            // ══════════════════ GDAŃSK ══════════════════

            [
                'title' => 'Billboard DK7 Gdańsk - obok stacji paliw',
                'type' => 'billboard',
                'location' => 'ul. Kartuska 245',
                'city' => 'Gdańsk',
                'region' => 'pomorskie',
                'latitude' => 54.3421,
                'longitude' => 18.5932,
                'description' => "Billboard przy Kartuskiej, DK7 w kierunku Kartuz. Stoi obok stacji paliw, więc kierowcy i tak zwalniają. Jednostronny, LED, 6x3m. Od miesiąca, przy kwartale daję rabat. Formularz.",
                'price' => 1900,
                'price_unit' => 'month',
                'width' => 6.00,
                'height' => 3.00,
                'variant' => 'standard',
                'road_class' => 'national',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['vehicular'],
                'has_backlight' => true,
                'offer_type' => 'owner',
            ],
            [
                'title' => 'Citylight Łostowice Gdańsk - duże osiedle',
                'type' => 'citylight',
                'location' => 'ul. Łostowicka 93',
                'city' => 'Gdańsk',
                'region' => 'pomorskie',
                'latitude' => 54.3312,
                'longitude' => 18.5821,
                'description' => "Łostowice to blokowisko z lat 80. - kilkanaście tysięcy mieszkańców i prawie wszyscy jeżdżą autobusem bo tramwaj tu nie dociera. Przystanek przy Łostowickiej jest głównym węzłem - staje tu linia 110, 122 i 158. Podświetlany, 120x180 cm. Ramka ma drobne zarysowania po kilku latach użytkowania, ale sam panel świeci równo i grafikę widać dobrze.",
                'price' => 650,
                'price_unit' => 'month',
                'width' => 1.20,
                'height' => 1.80,
                'variant' => 'single_sided',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['pedestrian'],
                'has_backlight' => true,
                'offer_type' => 'owner',
            ],
            [
                'title' => 'Ogrodzenie pod baner - strefa portowa Nowy Port',
                'type' => 'banner',
                'location' => 'ul. Majowa 2',
                'city' => 'Gdańsk',
                'region' => 'pomorskie',
                'latitude' => 54.3891,
                'longitude' => 18.6612,
                'description' => "Ogrodzenie przy działce w Nowym Porcie - strefa portowa, jedzie tamtędy sporo ciężarówek i dostawczaków. Miejsce na baner do 12x2m. Grafika we własnym zakresie. Piszcie przez formularz.",
                'price' => 900,
                'price_unit' => 'month',
                'width' => 12.00,
                'height' => 2.00,
                'traffic_intensity' => 'medium',
                'traffic_type' => ['vehicular'],
                'has_backlight' => false,
                'lighting_type_banner' => 'none',
                'offer_type' => 'owner',
                'price_negotiable' => true,
            ],

            // ══════════════════ ŁÓDŹ ══════════════════

            [
                'title' => 'Billboard Widzew Łódź dostępny od zaraz',
                'type' => 'billboard',
                'location' => 'ul. Brzezińska 37',
                'city' => 'Łódź',
                'region' => 'lodzkie',
                'latitude' => 51.7712,
                'longitude' => 19.5034,
                'description' => "Billboard przy Brzezińskiej na Widzewie - ulica jest mocno zakorkowana wieczorami bo to główny dojazd ze wschodnich części Łodzi. Jednostronny, oświetlony, standard 504x238. Mam możliwość wymiany grafiki co miesiąc, sam organizuję druk za dodatkową opłatą jeśli potrzeba.",
                'price' => 1100,
                'price_unit' => 'month',
                'width' => 5.04,
                'height' => 2.38,
                'variant' => 'standard',
                'road_class' => 'urban',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['vehicular'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'price_negotiable' => true,
            ],

            // ══════════════════ KATOWICE ══════════════════

            [
                'title' => 'Billboard południe Katowic - wyjazd na S86',
                'type' => 'billboard',
                'location' => 'ul. Murckowska 14',
                'city' => 'Katowice',
                'region' => 'slaskie',
                'latitude' => 50.2398,
                'longitude' => 19.0412,
                'description' => "Billboard przy Murckowskiej, wylot na S86. Jednostronny, podświetlany LED, stan dobry. Minimum 3 miesiące, faktura VAT. Szczegóły przez formularz.",
                'price' => 1600,
                'price_unit' => 'month',
                'width' => 5.04,
                'height' => 2.38,
                'variant' => 'standard',
                'road_class' => 'urban',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['vehicular'],
                'has_backlight' => true,
                'offer_type' => 'owner',
            ],
            [
                'title' => 'Panel na przystanku tramwajowym Koszutka Katowice',
                'type' => 'citylight',
                'location' => 'ul. Rolna 43',
                'city' => 'Katowice',
                'region' => 'slaskie',
                'latitude' => 50.2589,
                'longitude' => 19.0078,
                'description' => "Koszutka to stara robotnicza dzielnica - przystanek przy Rolnej obsługuje głównie ludzi jadących na pierwszą zmianę i wracających po pracy. Tramwaje 6 i 15, rano w obie strony tłoczno. Powiem szczerze: tutaj reklama działa lepiej dla usług lokalnych niż dla marek premium - publika jest pragmatyczna. Apteka, sklep, serwis - strzał w dziesiątkę. Podświetlany, dostępny od zaraz.",
                'price' => 680,
                'price_unit' => 'month',
                'width' => 1.20,
                'height' => 1.80,
                'variant' => 'single_sided',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['pedestrian'],
                'has_backlight' => true,
                'offer_type' => 'owner',
            ],

            // ══════════════════ SZCZECIN ══════════════════

            [
                'title' => 'Billboard Niebuszewo Szczecin - dostępny od zaraz',
                'type' => 'billboard',
                'location' => 'ul. Andrzeja Struga 15',
                'city' => 'Szczecin',
                'region' => 'zachodniopomorskie',
                'latitude' => 53.4312,
                'longitude' => 14.5678,
                'description' => "Billboard przy ul. Struga na Niebuszewie. Spokojniejsza dzielnica ale tranzyt stąd do centrum jest spory. Jednostronny, stan dobry, oświetlenie działa. Właśnie skończyła się umowa poprzedniego klienta więc jest od razu dostępny. Wolę kontakt przez wiadomość.",
                'price' => 1200,
                'price_unit' => 'month',
                'width' => 5.04,
                'height' => 2.38,
                'variant' => 'standard',
                'road_class' => 'urban',
                'traffic_intensity' => 'low',
                'traffic_type' => ['vehicular'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'price_negotiable' => true,
            ],

            // ══════════════════ LUBLIN ══════════════════

            [
                'title' => 'Billboard wylot z Lublina - droga krajowa na Kraśnik',
                'type' => 'billboard',
                'location' => 'ul. Kraśnicka 178',
                'city' => 'Lublin',
                'region' => 'lubelskie',
                'latitude' => 51.2165,
                'longitude' => 22.5012,
                'description' => "Mam billboard przy Kraśnickiej na wylocie z Lublina w stronę Kraśnika. Droga bardzo ruchliwa - dużo busów i tirów, bo to ważny tranzyt na południe. Nośnik jednostronny, skierowany na wyjazd z miasta. Oświetlony, cena za miesiąc, przy dłuższej umowie jest pole do rozmowy.",
                'price' => 1350,
                'price_unit' => 'month',
                'width' => 5.04,
                'height' => 2.38,
                'variant' => 'standard',
                'road_class' => 'national',
                'traffic_intensity' => 'high',
                'traffic_type' => ['vehicular'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'price_negotiable' => true,
            ],
            [
                'title' => 'Dwustronny pylon przy galerii Atrium - Lublin Czuby',
                'type' => 'totem',
                'location' => 'ul. Tomasza Zana 38',
                'city' => 'Lublin',
                'region' => 'lubelskie',
                'latitude' => 51.2298,
                'longitude' => 22.5234,
                'description' => "Pylon dwustronny przy ul. Zana, między galerią Atrium a osiedlem Czuby Północne. Duże osiedle, mnóstwo mieszkańców, blisko galeria i kilka sklepów. Dobra ekspozycja dla usług lokalnych - przychodnia, restauracja, sklep. Podświetlany LED, format 1,2x3m. Dostępny od zaraz.",
                'price' => 1100,
                'price_unit' => 'month',
                'width' => 1.20,
                'height' => 3.00,
                'variant' => 'double_sided',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['pedestrian', 'vehicular'],
                'has_backlight' => true,
                'offer_type' => 'owner',
            ],

            // ══════════════════ BYDGOSZCZ ══════════════════

            [
                'title' => 'Naklejka reklamowa na taksówce - Bydgoszcz, głównie Śródmieście',
                'type' => 'mobile',
                'location' => 'Bydgoszcz',
                'city' => 'Bydgoszcz',
                'region' => 'kujawsko-pomorskie',
                'latitude' => 53.1235,
                'longitude' => 18.0084,
                'description' => "Jeżdżę taksówką po Bydgoszczy, głównie centrum, Fordon i okolice dworca. Mam wolne miejsce na naklejkę z tyłu szyby i ewentualnie boki. Pracuję 5-6 dni w tygodniu. Kontakt przez formularz.",
                'price' => 150,
                'price_unit' => 'month',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['vehicular', 'pedestrian'],
                'variant' => 'car',
                'has_backlight' => false,
                'offer_type' => 'owner',
                'mobile_exposure_mode' => 'moving',
                'route_area' => 'Bydgoszcz - Śródmieście, Fordon, dworzec',
                'vehicle_count' => 1,
                'operating_hours' => '07:00-20:00',
                'price_negotiable' => true,
            ],
            [
                'title' => 'Przyczepka reklamowa do wynajęcia - Bydgoszcz i okolice',
                'type' => 'mobile',
                'location' => 'Bydgoszcz',
                'city' => 'Bydgoszcz',
                'region' => 'kujawsko-pomorskie',
                'latitude' => 53.1189,
                'longitude' => 18.0034,
                'description' => "Mam przyczepkę z dwustronną tablicą reklamową 2x1m, stawiam w uzgodnionym miejscu na czas kampanii. Sprawdza się przy targach, przy sklepach, na rondach. Bydgoszcz i okolice do 30 km. Cena za tydzień lub miesiąc, dogadamy się. Kontakt przez formularz.",
                'price' => 350,
                'price_unit' => 'week',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['vehicular', 'pedestrian'],
                'variant' => 'trailer',
                'has_backlight' => false,
                'offer_type' => 'owner',
                'mobile_exposure_mode' => 'stationary',
                'route_area' => 'Bydgoszcz i okolice do 30 km',
                'vehicle_count' => 1,
                'price_negotiable' => true,
            ],

            // ══════════════════ RZESZÓW ══════════════════

            [
                'title' => 'Billboard dwustronny centrum Rzeszowa - przy dworcu',
                'type' => 'billboard',
                'location' => 'al. Leopolda Lisa-Kuli 19',
                'city' => 'Rzeszów',
                'region' => 'podkarpackie',
                'latitude' => 50.0412,
                'longitude' => 22.0023,
                'description' => "Billboard przy głównej alei w centrum Rzeszowa, niedaleko dworca. Rzeszów szybko rośnie i ruch w centrum jest coraz większy. Nośnik dwustronny, widoczny zarówno od strony ronda jak i w kierunku galerii. Sam mam kilka nośników w mieście - ten jest najlepiej zlokalizowany z całej mojej oferty. Cena miesięczna, możliwa faktura.",
                'price' => 2100,
                'price_unit' => 'month',
                'width' => 6.00,
                'height' => 3.00,
                'variant' => 'two_sided',
                'road_class' => 'urban',
                'traffic_intensity' => 'high',
                'traffic_type' => ['vehicular', 'pedestrian'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'has_vat_invoice' => true,
            ],

            // ══════════════════ OKOLICE WARSZAWY ══════════════════

            [
                'title' => 'Billboard przy Puławskiej - Piaseczno, korki i długa ekspozycja',
                'type' => 'billboard',
                'location' => 'ul. Puławska 34',
                'city' => 'Piaseczno',
                'region' => 'mazowieckie',
                'latitude' => 52.0823,
                'longitude' => 21.0167,
                'description' => "Nośnik przy Puławskiej w Piasecznie, kilkaset metrów za granicą Warszawy. Jeden z głównych wyjazdów z południa aglomeracji - korki tu stoją codziennie rano i wieczorem, więc czas ekspozycji jest naprawdę długi. Jednostronny 6x3m, oświetlony. Poprzedni najemca miał salon samochodowy - polecam ten typ branży.",
                'price' => 1800,
                'price_unit' => 'month',
                'width' => 6.00,
                'height' => 3.00,
                'variant' => 'standard',
                'road_class' => 'national',
                'traffic_intensity' => 'high',
                'traffic_type' => ['vehicular'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'price_negotiable' => true,
            ],
            [
                'title' => 'Citylight PKP Pruszków - tysiące pasażerów dziennie',
                'type' => 'citylight',
                'location' => 'ul. Bohaterów Warszawy 2',
                'city' => 'Pruszków',
                'region' => 'mazowieckie',
                'latitude' => 52.1689,
                'longitude' => 20.8012,
                'description' => "Panel reklamowy przy wejściu na stację PKP Pruszków. Codziennie kilka tysięcy dojeżdżających do Warszawy - większość to osoby w wieku 25–50 lat, pracujące. Ekspozycja bardzo dobra bo ludzie stoją i czekają na peron. Format 120x180cm, podświetlany, stan bdb. Dostępny od następnego miesiąca.",
                'price' => 780,
                'price_unit' => 'month',
                'width' => 1.20,
                'height' => 1.80,
                'variant' => 'single_sided',
                'traffic_intensity' => 'high',
                'traffic_type' => ['pedestrian'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'estimated_daily_views' => 4200,
            ],

            // ══════════════════ DROGI KRAJOWE / EKSPRESOWE ══════════════════

            [
                'title' => 'Billboard DK7 Białobrzegi kierunek Warszawa',
                'type' => 'billboard',
                'location' => 'ul. Warszawska 112',
                'city' => 'Białobrzegi',
                'region' => 'mazowieckie',
                'latitude' => 51.6589,
                'longitude' => 20.9456,
                'description' => "Billboard przy drodze krajowej nr 7 między Radomiem a Warszawą, miejscowość Białobrzegi. Trasa bardzo uczęszczana - jedyna prosta droga z południa Mazowsza do stolicy. Nośnik jednostronny skierowany na Warszawę, widoczny z daleka bo teren otwarty. Idealne dla firm z branży transportowej, budowlanej albo deweloperów z okolic Radomia. Cena negocjowalna przy umowie minimum 3 miesiące.",
                'price' => 1450,
                'price_unit' => 'month',
                'width' => 6.00,
                'height' => 3.00,
                'variant' => 'standard',
                'road_class' => 'national',
                'traffic_intensity' => 'high',
                'traffic_type' => ['vehicular'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'price_negotiable' => true,
            ],
            [
                'title' => 'Billboard przy MOP Adamowice - S8, 45 km od Warszawy',
                'type' => 'billboard',
                'location' => 'Mszczonów, MOP Adamowice',
                'city' => 'Mszczonów',
                'region' => 'mazowieckie',
                'latitude' => 51.9712,
                'longitude' => 20.5234,
                'description' => "Billboard przy MOP Adamowice na S8 - kierowcy się tu zatrzymują więc czas ekspozycji jest spory. Dwustronny 6x3m, LED. Mam ten nośnik od kilku lat, zawsze był zajęty. Kontakt przez formularz, minimum 3 miesiące.",
                'price' => 3200,
                'price_unit' => 'month',
                'width' => 6.00,
                'height' => 3.00,
                'variant' => 'two_sided',
                'road_class' => 'expressway',
                'traffic_intensity' => 'high',
                'traffic_type' => ['vehicular'],
                'has_backlight' => true,
                'offer_type' => 'agency',
                'estimated_daily_views' => 20000,
            ],
            [
                'title' => 'Billboard przy DK1 za Piotrkowem - trasa na Śląsk, wolny po 8 latach',
                'type' => 'billboard',
                'location' => 'ul. Sulejowska 201',
                'city' => 'Piotrków Trybunalski',
                'region' => 'lodzkie',
                'latitude' => 51.3789,
                'longitude' => 19.7023,
                'description' => "Stary, sprawdzony nośnik przy DK1 za Piotrkowem jadąc na południe. Trasa na Częstochowę i Śląsk, zawsze spory ruch - szczególnie TIRy i busy. Billboard jednostronny, skierowany na kierowców jadących na południe. Oświetlony. Mam go już od 8 lat i zawsze był wynajęty - dopiero teraz jest wolny po poprzednim kliencie.",
                'price' => 1250,
                'price_unit' => 'month',
                'width' => 5.04,
                'height' => 2.38,
                'variant' => 'standard',
                'road_class' => 'national',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['vehicular'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'price_negotiable' => true,
            ],

            // ══════════════════ MNIEJSZE MIASTA ══════════════════

            [
                'title' => 'Ekran LED centrum Kielc - przy przejściu dla pieszych',
                'type' => 'led_screen',
                'location' => 'ul. Tadeusza Kościuszki 8',
                'city' => 'Kielce',
                'region' => 'swietokrzyskie',
                'latitude' => 50.8661,
                'longitude' => 20.6331,
                'description' => "Ekran LED w ścisłym centrum Kielc, przy głównej ulicy handlowej. Lokalizacja przy przejściu dla pieszych z długim cyklem świetlnym - idealna ekspozycja dla pieszych i zatrzymanych kierowców. Rozdzielczość Full HD, jasność 6000 nitów, praca 24/7. Sprzedajemy czas emisji w blokach tygodniowych (min. 2 tygodnie) lub miesięcznych. Cena za emisję w rotacji - wyłączność do uzgodnienia.",
                'price' => 2200,
                'price_unit' => 'month',
                'width' => 3.00,
                'height' => 2.00,
                'resolution' => '1920x1080',
                'pixel_pitch' => 8,
                'brightness' => 6000,
                'ambient_light_control' => true,
                'traffic_intensity' => 'medium',
                'traffic_type' => ['pedestrian', 'vehicular'],
                'has_backlight' => true,
                'offer_type' => 'agency',
                'variant' => 'standard',
                'environment' => 'outdoor',
            ],
            [
                'title' => 'Ogrodzenie pod baner - wjazd do Tarnowa od strony Krakowa',
                'type' => 'banner',
                'location' => 'ul. Krakowska 153',
                'city' => 'Tarnów',
                'region' => 'malopolskie',
                'latitude' => 50.0134,
                'longitude' => 20.9723,
                'description' => "Mam ogrodzenie przy swojej działce przy Krakowskiej w Tarnowie i mogę je udostępnić pod baner. Działka stoi przy wjeździe do miasta od strony Krakowa - sporo aut tamtędy jedzie zwłaszcza przez wakacje i weekendy. Miejsce na baner mniej więcej 8x2m, mogę przygotować punkty montażowe. Cena do negocjacji, wolę dłuższy wynajem.",
                'price' => 600,
                'price_unit' => 'month',
                'width' => 8.00,
                'height' => 2.00,
                'traffic_intensity' => 'medium',
                'traffic_type' => ['vehicular'],
                'has_backlight' => false,
                'lighting_type_banner' => 'none',
                'offer_type' => 'owner',
                'price_negotiable' => true,
                'environment' => 'outdoor',
            ],
            [
                'title' => 'Citylight centrum Olsztyna - ruchliwy przystanek tramwajowy',
                'type' => 'citylight',
                'location' => 'al. Piłsudskiego 38',
                'city' => 'Olsztyn',
                'region' => 'warminsko-mazurskie',
                'latitude' => 53.7784,
                'longitude' => 20.4801,
                'description' => "Al. Piłsudskiego to główna ulica Olsztyna - przystanek blisko galerii i kilku biur. Staje tu 1 i 3 tramwaj plus autobusy podmiejskie z okolicznych gmin. W piątki po południu naprawdę spory tłum dojeżdżających. Format 120x180, podświetlany. Mogę wymieniać grafikę samodzielnie co miesiąc jeśli potrzebujesz - usługa za dodatkową opłatą, cena do dogadania.",
                'price' => 620,
                'price_unit' => 'month',
                'width' => 1.20,
                'height' => 1.80,
                'variant' => 'single_sided',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['pedestrian'],
                'has_backlight' => true,
                'offer_type' => 'owner',
            ],
            [
                'title' => 'Naklejka reklamowa na taksówce - Warszawa, centrum i Mokotów codziennie',
                'type' => 'mobile',
                'location' => 'Warszawa',
                'city' => 'Warszawa',
                'region' => 'mazowieckie',
                'latitude' => 52.2297,
                'longitude' => 21.0122,
                'description' => "Jeżdżę taksówką po Warszawie od 6 lat, głównie Śródmieście, Mokotów, Wola, czasem Ursynów i Wilanów. Pracuję codziennie ok. 10-12 godzin. Mam miejsce na naklejkę z tyłu auta i mogę wozić ulotki w środku dla pasażerów. Tanio, ale skutecznie - każdy pasażer siedzi i patrzy. Kontakt przez wiadomość.",
                'price' => 200,
                'price_unit' => 'month',
                'traffic_intensity' => 'high',
                'traffic_type' => ['vehicular', 'pedestrian'],
                'variant' => 'car',
                'has_backlight' => false,
                'offer_type' => 'owner',
                'mobile_exposure_mode' => 'moving',
                'route_area' => 'Warszawa - Śródmieście, Mokotów, Wola',
                'vehicle_count' => 1,
                'operating_hours' => '07:00-19:00',
                'price_negotiable' => true,
            ],
            [
                'title' => 'Billboard Lubin wjazd od A4 - miasto KGHM',
                'type' => 'billboard',
                'location' => 'ul. Legnicka 84',
                'city' => 'Lubin',
                'region' => 'dolnoslaskie',
                'latitude' => 51.4023,
                'longitude' => 16.2134,
                'description' => "Billboard przy drodze z autostrady A4 do Lubina. Lubin to miasto KGHM - dużo firm dostawczych, pracowników i kontrahentów tamtędy jeździ. Nośnik jednostronny skierowany na wjazd do miasta. Stan dobry, oświetlony. Cena miesięczna, wystawiam fakturę.",
                'price' => 1050,
                'price_unit' => 'month',
                'width' => 5.04,
                'height' => 2.38,
                'variant' => 'standard',
                'road_class' => 'urban',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['vehicular'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'has_vat_invoice' => true,
            ],
            [
                'title' => 'Ściana na kamienicy przy Rynku - Wieliczka, blisko Kopalni Soli',
                'type' => 'wall',
                'location' => 'Rynek 15',
                'city' => 'Wieliczka',
                'region' => 'malopolskie',
                'latitude' => 49.9878,
                'longitude' => 20.0645,
                'description' => "Ściana reklamowa na kamienicy przy Rynku w Wieliczce - kilkaset metrów od wejścia do Kopalni Soli. Przez Wieliczkę przejeżdżają setki tysięcy turystów rocznie. Powierzchnia 6x4m, boczna elewacja widoczna z Rynku. Polecam firmom turystycznym, restauracjom, hotelom z okolic Krakowa. Minimum 3 miesiące, możliwa umowa sezonowa.",
                'price' => 2800,
                'price_unit' => 'month',
                'width' => 6.00,
                'height' => 4.00,
                'traffic_intensity' => 'high',
                'traffic_type' => ['pedestrian', 'vehicular'],
                'has_backlight' => false,
                'lighting_type_banner' => 'none',
                'offer_type' => 'owner',
                'price_negotiable' => true,
            ],


            // ══════════════════ PREMIUM / BUDŻET / Z CHARAKTEREM ══════════════════

            [
                'title' => 'Billboard premium Śródmieście Warszawa - Marszałkowska/Świętokrzyska',
                'type' => 'billboard',
                'location' => 'ul. Marszałkowska 68',
                'city' => 'Warszawa',
                'region' => 'mazowieckie',
                'latitude' => 52.2312,
                'longitude' => 21.0089,
                'description' => "Nośnik w sercu Warszawy, skrzyżowanie Marszałkowskiej i Świętokrzyskiej - zaraz przy wejściu do metra. Dobowy ruch pieszy przekracza 25 000 osób, plus kierowcy. Dwustronny 6x3m, oświetlenie LED, stan b.d.b. Zarządzamy kilkoma nośnikami w centrum - ten jest naszym flagowym. Możliwość emisji w wyłączności lub rotacji max 3 klientów. Cena netto, faktura VAT 23%, minimalna umowa 1 miesiąc.",
                'price' => 4200,
                'price_unit' => 'month',
                'width' => 6.00,
                'height' => 3.00,
                'variant' => 'two_sided',
                'road_class' => 'urban',
                'traffic_intensity' => 'high',
                'traffic_type' => ['vehicular', 'pedestrian'],
                'has_backlight' => true,
                'offer_type' => 'agency',
                'has_vat_invoice' => true,
            ],
            [
                'title' => 'Billboard wjazd do Nowego Sącza od strony Krakowa - tani',
                'type' => 'billboard',
                'location' => 'ul. Krakowska 178',
                'city' => 'Nowy Sącz',
                'region' => 'malopolskie',
                'latitude' => 49.6234,
                'longitude' => 20.6887,
                'description' => "Mam billboard przy Krakowskiej w Nowym Sączu - droga wjazdowa od strony Krakowa. Każdy kto jedzie do Sącza z zachodu go mija. Powiem szczerze: cena jest niska bo to obrzeża i Nowy Sącz to nie Kraków - ale dla lokalnej firmy z okolicy w zupełności wystarczy. Do odnowienia malowanie słupa, ale konstrukcja i panel są w dobrym stanie. Jednostronny, oświetlony. Minimalna umowa 2 miesiące.",
                'price' => 550,
                'price_unit' => 'month',
                'width' => 5.04,
                'height' => 2.38,
                'variant' => 'standard',
                'road_class' => 'national',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['vehicular'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'price_negotiable' => true,
            ],
            [
                'title' => 'Billboard przy DK8 Pułtusk - dobry na lato, tani bo zasłonięty',
                'type' => 'billboard',
                'location' => 'ul. Białowiejska 11',
                'city' => 'Pułtusk',
                'region' => 'mazowieckie',
                'latitude' => 52.7123,
                'longitude' => 21.0845,
                'description' => "Billboard przy drodze krajowej nr 8 za Pułtuskiem jadąc z Warszawy na Białystok. Powiem o problemie wprost, żebyś wiedział na co się piszesz: po lewej stronie rośnie dąb i od maja do października trochę zasłania panel od zachodu, szczególnie po południu. Zimą i wczesną wiosną widoczność jest pełna. Właśnie dlatego daję to tanio. Ruch na DK8 jest spory - ciągłe tiry i osobówki. Jednostronny, oświetlony.",
                'price' => 680,
                'price_unit' => 'month',
                'width' => 5.04,
                'height' => 2.38,
                'variant' => 'standard',
                'road_class' => 'national',
                'traffic_intensity' => 'medium',
                'traffic_type' => ['vehicular'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'price_negotiable' => true,
            ],
            [
                'title' => 'Citylight przystanek Piłsudskiego Wrocław - wysoki ruch, uczciwa cena',
                'type' => 'citylight',
                'location' => 'ul. Piłsudskiego 105',
                'city' => 'Wrocław',
                'region' => 'dolnoslaskie',
                'latitude' => 51.0982,
                'longitude' => 17.0378,
                'description' => "Przystanek przy Piłsudskiego niedaleko dworca - staje tu z 8 linii i ruch jest naprawdę duży przez całą dobę. Jedna rzecz do powiedzenia: wieczorami kręci się przy tym przystanku sporo bezdomnych. Sam panel jest w dobrej formie, ale to nie jest środowisko premium - mówię to uczciwie. Dla fast-foodów, sklepów dyskontowych, usług lokalnych - działa doskonale. Dla marki luksusowej pewnie nie ta lokalizacja. Podświetlany, format standardowy.",
                'price' => 720,
                'price_unit' => 'month',
                'width' => 1.20,
                'height' => 1.80,
                'variant' => 'single_sided',
                'traffic_intensity' => 'high',
                'traffic_type' => ['pedestrian'],
                'has_backlight' => true,
                'offer_type' => 'owner',
                'price_negotiable' => true,
            ],

        ];

        $defaults = [
            'owner_email'             => 'test@test.pl',
            'phone'                   => '',
            'contact_preference'      => 'form',
            'is_active'               => true,
            'is_verified'             => true,
            'has_image'               => false,
            'images'                  => [],
            'has_vat_invoice'         => true,
            'price_includes_print'    => false,
            'price_includes_mounting' => false,
            'graphic_design_help'     => false,
            'price_negotiable'        => false,
            'status'                  => 'active',
        ];

        // Daty dodania - wszystkie w kwietniu 2026
        $createdDates = [
            Carbon::create(2026, 4, 1, 9, 12),
            Carbon::create(2026, 4, 1, 14, 33),
            Carbon::create(2026, 4, 2, 8, 55),
            Carbon::create(2026, 4, 2, 17, 21),
            Carbon::create(2026, 4, 3, 10, 44),
            Carbon::create(2026, 4, 3, 13, 07),
            Carbon::create(2026, 4, 4, 9, 30),
            Carbon::create(2026, 4, 4, 16, 18),
            Carbon::create(2026, 4, 5, 11, 52),
            Carbon::create(2026, 4, 6, 8, 40),
            Carbon::create(2026, 4, 6, 15, 29),
            Carbon::create(2026, 4, 7, 10, 15),
            Carbon::create(2026, 4, 7, 18, 03),
            Carbon::create(2026, 4, 8, 9, 47),
            Carbon::create(2026, 4, 8, 14, 22),
            Carbon::create(2026, 4, 9, 11, 38),
            Carbon::create(2026, 4, 9, 16, 55),
            Carbon::create(2026, 4, 10, 8, 20),
            Carbon::create(2026, 4, 10, 13, 44),
            Carbon::create(2026, 4, 11, 9, 58),
            Carbon::create(2026, 4, 11, 17, 31),
            Carbon::create(2026, 4, 12, 10, 06),
            Carbon::create(2026, 4, 12, 15, 48),
            Carbon::create(2026, 4, 13, 9, 12),
            Carbon::create(2026, 4, 13, 14, 37),
            Carbon::create(2026, 4, 13, 19, 02),
            Carbon::create(2026, 4, 14, 8, 33),
            Carbon::create(2026, 4, 14, 10, 19),
            Carbon::create(2026, 4, 14, 11, 45),
            Carbon::create(2026, 4, 14, 12, 28),
            Carbon::create(2026, 4, 14, 13, 55),
            Carbon::create(2026, 4, 14, 14, 41),
            Carbon::create(2026, 4, 14, 15, 17),
            Carbon::create(2026, 4, 14, 16, 03),
            Carbon::create(2026, 4, 14, 17, 22),
            Carbon::create(2026, 4, 15, 9, 15),
            Carbon::create(2026, 4, 15, 11, 43),
            Carbon::create(2026, 4, 15, 14, 28),
            Carbon::create(2026, 4, 15, 16, 55),
        ];

        foreach ($ads as $index => $ad) {
            $data = array_merge($defaults, $ad);

            if (isset($data['width'], $data['height'])) {
                $data['orientation'] = $data['width'] >= $data['height'] ? 'horizontal' : 'vertical';
            }

            $data['rental_period'] = in_array($data['price_unit'] ?? '', ['day', 'week']) ? 'short_term' : 'long_term';

            $data['slug'] = Str::slug($data['title']);

            // Przypisz datę dodania
            $createdAt = $createdDates[$index] ?? now()->subDays(rand(1, 30));

            // Ogłoszenia dostępne od konkretnej daty (nie od zaraz)
            $availableFrom = [
                2  => Carbon::create(2026, 4, 25), // Bródno - "najem miesięczny lub dłużej"
                4  => Carbon::create(2026, 4, 22), // Kraków Półkole - dopiero udostępnia
                6  => Carbon::create(2026, 5, 1),  // Kraków LED Podgórze - agencja, cykl miesięczny
                7  => Carbon::create(2026, 5, 1),  // Wrocław Kosmonautów - wolny od maja
                11 => Carbon::create(2026, 5, 1),  // Poznań pylon - opis: "od początku przyszłego miesiąca"
                12 => Carbon::create(2026, 4, 28), // Gdańsk DK7 - zarządca OutMedia
                24 => Carbon::create(2026, 5, 1),  // Pruszków PKP - opis: "od następnego miesiąca"
                27 => Carbon::create(2026, 4, 20), // Piotrków DK1 - "wolny po poprzednim kliencie"
                29 => Carbon::create(2026, 5, 10), // Tarnów - "wolę dłuższy wynajem"
                33 => Carbon::create(2026, 4, 18), // Wieliczka wall - min. 3 miesiące
                36 => Carbon::create(2026, 5, 1),  // Pułtusk DK8 - problem z dębem, nie pilno
            ];
            if (isset($availableFrom[$index])) {
                $data['available_from'] = $availableFrom[$index];
            }

            $ad = Advertisement::updateOrCreate(
                ['slug' => $data['slug']],
                $data
            );

            // Ustaw datę created_at ręcznie (poza fillable)
            $ad->timestamps = false;
            $ad->created_at = $createdAt;
            $ad->updated_at = $createdAt;
            $ad->save();
            $ad->timestamps = true;
        }

        $this->command->info('Dodano ' . count($ads) . ' ogłoszeń. Email zarządzania: test@test.pl');
    }
}
