<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Advertisement;
use Illuminate\Support\Str;

class RealisticAdvertisementsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ads = [
            // ================= WARSZAWA =================
            [
                'title' => 'Siatka wielkoformatowa - Rondo Dmowskiego',
                'type' => 'wall',
                'location' => 'Aleje Jerozolimskie 44',
                'city' => 'Warszawa',
                'region' => 'mazowieckie',
                'latitude' => 52.2297,
                'longitude' => 21.0122,
                'description' => "Cześć, oferuję pod wynajem miejsce na ogromną siatkę reklamową przy samym rondzie Dmowskiego. Miejsce to po prostu petarda, w samym centrum Warszawy. Z rogu idealnie widać baner z różnych stron. Mnóstwo ludzi przewija się tam pieszo i w samochodach. Jeśli chcesz, aby Twoja marka była widoczna dla każdego, kto jest w centrum, to szczerze polecam. Dostępna od zaraz.\n\nW razie pytań zapraszam do kontaktu przez formularz.",
                'price' => 45000,
                'price_unit' => 'month',
                'width' => 20.00,
                'height' => 15.00,
                'traffic_intensity' => 'high',
                'status' => 'active',
                'has_backlight' => true,
                'lighting_type_banner' => 'frontlight',
            ],
            [
                'title' => 'Ekran LED przy Świętokrzyskiej',
                'type' => 'led_screen',
                'location' => 'ul. Świętokrzyska 11',
                'city' => 'Warszawa',
                'region' => 'mazowieckie',
                'latitude' => 52.2359,
                'longitude' => 21.0113,
                'description' => "Mam wolny czas antenowy na nowoczesnym ekranie LED zaraz przy stacji metra Świętokrzyska. Bardzo wyraźny obraz, niska awaryjność. Skrzyżowanie zawsze bardzo zapracowane, wokół same biurowce i sklepy, więc puszczany spot łapie świetne pokrycie. Mogę ustawić na konkretne godziny lub puścić w rotacji przez cały dzień.",
                'price' => 8000,
                'price_unit' => 'month',
                'width' => 8.00,
                'height' => 4.00,
                'resolution' => '1920x1080',
                'pixel_pitch' => '6',
                'brightness' => '8500',
                'ambient_light_control' => true,
                'traffic_intensity' => 'high',
                'status' => 'active',
                'has_backlight' => true,
            ],
            [
                'title' => 'Billboard Rondo ONZ',
                'type' => 'billboard',
                'location' => 'Rondo ONZ 1',
                'city' => 'Warszawa',
                'region' => 'mazowieckie',
                'latitude' => 52.2327,
                'longitude' => 20.9985,
                'description' => "Oferuję wolny billboard 12x4 dwustronny zamontowany przy Rondzie ONZ. Obok same wieżowce, spory ruch aut non stop. Oświetlenie ulepszyliśmy na LED, żeby widać było z daleka nocą. Cena do lekkiej negocjacji przy dłuższej umowie. Zgłaszajcie się przez wiadomości.",
                'price' => 6000,
                'price_unit' => 'month',
                'width' => 12.00,
                'height' => 4.00,
                'variant' => 'two_sided',
                'traffic_intensity' => 'high',
                'status' => 'active',
                'has_backlight' => true,
            ],
            [
                'title' => 'Witryna Citylight na Marszałkowskiej',
                'type' => 'citylight',
                'location' => 'ul. Marszałkowska 104',
                'city' => 'Warszawa',
                'region' => 'mazowieckie',
                'latitude' => 52.2309,
                'longitude' => 21.0116,
                'description' => "Wynajmę panel citylight w rewelacyjnej lokacji na Marszałkowskiej. Bardzo dużo spacerujących tamtędy młodych ludzi, idealnie pod modę, knajpy albo kampanie miejskie. Konstrukcja solidna i podświetlana w nocy. Stawka za miesiąc z pełnym utrzymaniem.",
                'price' => 1200,
                'price_unit' => 'month',
                'width' => 1.20,
                'height' => 1.80,
                'variant' => 'double_sided',
                'traffic_intensity' => 'high',
                'status' => 'active',
                'has_backlight' => true,
            ],
            [
                'title' => 'Billboard na wyjeździe Puławska / Ursynów',
                'type' => 'billboard',
                'location' => 'ul. Puławska 427',
                'city' => 'Warszawa',
                'region' => 'mazowieckie',
                'latitude' => 52.1384,
                'longitude' => 20.0175,
                'description' => "Standardowy blaszak 12m, lokalizacja ulica Puławska na Ursynowie w stronę Piaseczna. Korek jest tam właściwie codziennie po południu, więc każdy będzie gapił się w Twoją reklamę z nudów! Dobra ekspozycja.",
                'price' => 1500,
                'price_unit' => 'month',
                'width' => 5.04,
                'height' => 2.38,
                'variant' => 'standard',
                'traffic_intensity' => 'medium',
                'status' => 'active',
                'has_backlight' => true,
            ],
            [
                'title' => 'Citylight Przystanek Pl. Zawiszy',
                'type' => 'citylight',
                'location' => 'Plac Artura Zawiszy',
                'city' => 'Warszawa',
                'region' => 'mazowieckie',
                'latitude' => 52.2250,
                'longitude' => 20.9880,
                'description' => "Oferuję powierzchnię wiaty na Pl. Zawiszy. Niesamowita wymiana pasażerów z tramwajów i busów. Do wynajęcia od początku przyszłego miesiąca.",
                'price' => 1800,
                'price_unit' => 'month',
                'width' => 1.20,
                'height' => 1.80,
                'variant' => 'single_sided',
                'traffic_intensity' => 'high',
                'status' => 'active',
                'has_backlight' => true,
            ],
            [
                'title' => 'Pakiet ekranów w Metrze - Stacja Świętokrzyska',
                'type' => 'transport',
                'location' => 'Stacja Metra Świętokrzyska',
                'city' => 'Warszawa',
                'region' => 'mazowieckie',
                'latitude' => 52.2351,
                'longitude' => 21.0084,
                'description' => "Jesteśmy operatorem i mamy pakiet na monitory na stacji krzyżówki metra. Jeśli zależy Ci na masowym odbiorcy, to jest to miejsce. Zrobimy na tym świetną zasięgową kampanię.",
                'price' => 9500,
                'price_unit' => 'month',
                'transport_scope' => 'internal',
                'vehicle_count' => 1,
                'variant' => 'metro',
                'traffic_intensity' => 'high',
                'status' => 'active',
            ],

            // ================= KRAKÓW =================
            [
                'title' => 'Billboard Rondo Matecznego - Hit',
                'type' => 'billboard',
                'location' => 'Rondo Antoniego Matecznego',
                'city' => 'Kraków',
                'region' => 'malopolskie',
                'latitude' => 50.0354,
                'longitude' => 19.9405,
                'description' => "Zwalnia się billboard przy jednym z najbardziej zapchanych rond w Krakowie :)\nGwarantuję świetną widoczność dla samochodów. Jak trzeba, to polecę zaufaną ekipę by to szybko wykleili na miejscu.",
                'price' => 2200,
                'price_unit' => 'month',
                'width' => 6.00,
                'height' => 3.00,
                'variant' => 'standard',
                'traffic_intensity' => 'high',
                'status' => 'active',
                'has_backlight' => true,
            ],
            [
                'title' => 'Siatka koło Wawelu na ul. Dietla',
                'type' => 'wall',
                'location' => 'ul. Dietla 50',
                'city' => 'Kraków',
                'region' => 'malopolskie',
                'latitude' => 50.0538,
                'longitude' => 19.9419,
                'description' => "Wyjątkowa pusta ściana naprzeciwko ruchu turystycznego na Kazimierz od Wisły. Czekamy na solidnego klienta, szukającego prestiżowego miejsca do reklamy. Konstrukcja wytrzymuje konkretne wichury, świeżo wymienione lampy oświetlające.",
                'price' => 8500,
                'price_unit' => 'month',
                'width' => 12.00,
                'height' => 14.00,
                'traffic_intensity' => 'high',
                'status' => 'active',
                'has_backlight' => true,
            ],
            [
                'title' => 'Telebim przy Alejach Trzech Wieszczów',
                'type' => 'led_screen',
                'location' => 'Al. Juliusza Słowackiego 15',
                'city' => 'Kraków',
                'region' => 'malopolskie',
                'latitude' => 50.0718,
                'longitude' => 19.9329,
                'description' => "Aleje w Krakowie wszyscy wiedzą jak jadą... wolno. Ekran wali po gałach w pozytywnym sensie (dostosowuje jasność sam). Miejsce doskonałe pod spoty wideo ok. 10-15 sekund np. koncerty, eventy albo premiery bankowe.",
                'price' => 4500,
                'price_unit' => 'month',
                'width' => 5.00,
                'height' => 3.00,
                'resolution' => '1024x768',
                'pixel_pitch' => '8',
                'traffic_intensity' => 'high',
                'status' => 'active',
                'has_backlight' => true,
            ],
            [
                'title' => 'Oklejenie Tramwaju MPK (Krakowiak)',
                'type' => 'transport',
                'location' => 'Zajezdnia Podgórze',
                'city' => 'Kraków',
                'region' => 'malopolskie',
                'latitude' => 50.0263,
                'longitude' => 19.9401,
                'description' => "Proponujemy wynajem wagonów całopojazdowych oklejonych siatką OWV na liniach krakowskich. Bardzo silny impakt w skali całego miasta, jeździ codziennie inną trasą, więc widzi go całe miasto.",
                'price' => 12000,
                'price_unit' => 'month',
                'transport_scope' => 'full_vehicle',
                'vehicle_count' => 1,
                'variant' => 'tram',
                'traffic_intensity' => 'medium',
                'status' => 'active',
            ],
            [
                'title' => 'Sukiennice Citylight z klasą',
                'type' => 'citylight',
                'location' => 'Rynek Główny 1',
                'city' => 'Kraków',
                'region' => 'malopolskie',
                'latitude' => 50.0617,
                'longitude' => 19.9373,
                'description' => "Super miejsce dla kogoś z luksusową marką (perfumy, biżuteria itp.). Mamy wolny tył citylighta z wejściem od Sukiennic od zaraz.",
                'price' => 3500,
                'price_unit' => 'month',
                'width' => 1.20,
                'height' => 1.80,
                'variant' => 'double_sided',
                'traffic_intensity' => 'high',
                'status' => 'active',
                'has_backlight' => true,
            ],

            // ================= WROCŁAW =================
            [
                'title' => 'Wolny Billboard Plac Grunwaldzki',
                'type' => 'billboard',
                'location' => 'Rondo Reagana',
                'city' => 'Wrocław',
                'region' => 'dolnoslaskie',
                'latitude' => 51.1118,
                'longitude' => 17.0601,
                'description' => "Rondo Grunwaldzkie wrze studencko i biurowo. Na tym billboardzie najlepiej sprawdzają się oferty pracy, promocje jedzeniowe albo telekomy. Wolny od następnego miesiąca. Zapraszam zainteresowanych.",
                'price' => 3100,
                'price_unit' => 'month',
                'width' => 6.00,
                'height' => 3.00,
                'variant' => 'standard',
                'traffic_intensity' => 'high',
                'status' => 'active',
                'has_backlight' => true,
            ],
            [
                'title' => 'Siatka na całą ścianę - Legnicka',
                'type' => 'wall',
                'location' => 'ul. Legnicka 50',
                'city' => 'Wrocław',
                'region' => 'dolnoslaskie',
                'latitude' => 51.1190,
                'longitude' => 16.9936,
                'description' => "Wynajmę ścianę ze stelażem. Duży ruch pod nosem w stronę Centrum. Możliwy wynajem w umowie co najmniej na kwartał. Zapraszam do rozmowy.",
                'price' => 7500,
                'price_unit' => 'month',
                'width' => 10.00,
                'height' => 15.00,
                'traffic_intensity' => 'high',
                'status' => 'active',
                'has_backlight' => true,
            ],
            [
                'title' => 'LED na Dominikańskim',
                'type' => 'led_screen',
                'location' => 'Plac Dominikański 3',
                'city' => 'Wrocław',
                'region' => 'dolnoslaskie',
                'latitude' => 51.1082,
                'longitude' => 17.0396,
                'description' => "Nasza gwiazda w ofercie. Ekran wielki, widoczny dla aut oczekujących na skręcie z P.D.",
                'price' => 6500,
                'price_unit' => 'month',
                'width' => 7.00,
                'height' => 4.00,
                'resolution' => '1280x720',
                'pixel_pitch' => '10',
                'traffic_intensity' => 'high',
                'status' => 'active',
                'has_backlight' => true,
            ],
            [
                'title' => 'Panel koło galerii Magnolia',
                'type' => 'citylight',
                'location' => 'ul. Legnicka 58',
                'city' => 'Wrocław',
                'region' => 'dolnoslaskie',
                'latitude' => 51.1192,
                'longitude' => 16.9835,
                'description' => "Citylight na alei dochodzącej prosto do Magnolia Park. Codziennie po prostu mnóstwo kupujących mija ten punkt.",
                'price' => 1100,
                'price_unit' => 'month',
                'width' => 1.20,
                'height' => 1.80,
                'variant' => 'single_sided',
                'traffic_intensity' => 'medium',
                'status' => 'active',
                'has_backlight' => true,
            ],

            // ================= POZNAŃ =================
            [
                'title' => 'Rondo Rataje - Duży format',
                'type' => 'billboard',
                'location' => 'Rondo Rataje',
                'city' => 'Poznań',
                'region' => 'wielkopolskie',
                'latitude' => 52.3965,
                'longitude' => 16.9531,
                'description' => "Blacha 18m2 w super punkcie - widok z dojazdu i na rondzie. Często stoją w korkach, na sygnalizacji świetlnej też chwilę.",
                'price' => 3200,
                'price_unit' => 'month',
                'width' => 6.00,
                'height' => 3.00,
                'variant' => 'standard',
                'traffic_intensity' => 'high',
                'status' => 'active',
                'has_backlight' => true,
            ],
            [
                'title' => 'Pylon reklamowy - Targi Poznańskie (MTP)',
                'type' => 'totem',
                'location' => 'ul. Głogowska 14',
                'city' => 'Poznań',
                'region' => 'wielkopolskie',
                'latitude' => 52.4042,
                'longitude' => 16.9126,
                'description' => "Oferta do wejścia ze swoją marką na pylon wystawiony vis a vis głównego dworca PKP/MTP. Jak rusza duża impreza targowa to to podłoże jest absolutnie kluczowe dla firm.",
                'price' => 2500,
                'price_unit' => 'month',
                'width' => 1.00,
                'height' => 3.50,
                'variant' => 'standard',
                'traffic_intensity' => 'medium',
                'status' => 'active',
                'has_backlight' => true,
            ],
            [
                'title' => 'Ekran RGB przy Starym Browarze',
                'type' => 'led_screen',
                'location' => 'ul. Półwiejska 32',
                'city' => 'Poznań',
                'region' => 'wielkopolskie',
                'latitude' => 52.4023,
                'longitude' => 16.9281,
                'description' => "Ekran z podwyższeniem bezpośrednio wpisany w architekturę. Najczęściej bierzemy kampanie kilkudniowe do miesiąca.",
                'price' => 5800,
                'price_unit' => 'month',
                'width' => 4.00,
                'height' => 3.00,
                'resolution' => '1024x768',
                'traffic_intensity' => 'high',
                'status' => 'active',
                'has_backlight' => true,
            ],
            [
                'title' => 'Oklejamy floty autobusowe autobusu',
                'type' => 'transport',
                'location' => 'Linie miejskie',
                'city' => 'Poznań',
                'region' => 'wielkopolskie',
                'latitude' => 52.4064,
                'longitude' => 16.9252,
                'description' => "Cześć, oklejamy tyły autokarów miejskich dla zasięgu. Dojeżdżają w każde osiedle w Poznaniu. Wynik GRP rośnie gigantycznie.",
                'price' => 3000,
                'price_unit' => 'month',
                'transport_scope' => 'external',
                'vehicle_count' => 5,
                'variant' => 'bus',
                'traffic_intensity' => 'medium',
                'status' => 'active',
            ],

            // ================= GDAŃSK =================
            [
                'title' => 'Wynajmę billboard przy Grunwaldzkiej',
                'type' => 'billboard',
                'location' => 'Al. Grunwaldzka 141',
                'city' => 'Gdańsk',
                'region' => 'pomorskie',
                'latitude' => 54.3812,
                'longitude' => 18.6010,
                'description' => "Puszka billboardu, lokalizacja w stronę Wrzeszcza od centrum przy Grunwaldzkiej. Klasyk klasyków.",
                'price' => 3800,
                'price_unit' => 'month',
                'width' => 6.00,
                'height' => 3.00,
                'variant' => 'standard',
                'traffic_intensity' => 'high',
                'status' => 'active',
                'has_backlight' => true,
            ],
            [
                'title' => 'Reklama Kolejki SKM (stacje)',
                'type' => 'citylight',
                'location' => 'Podwale Grodzkie 2',
                'city' => 'Gdańsk',
                'region' => 'pomorskie',
                'latitude' => 54.3557,
                'longitude' => 18.6444,
                'description' => "Cześć! Składam pakiety reklamy na peronach SKM (Gdańsk Główny, Wrzeszcz itp.). Bardzo dużo ludzi czytających z nudów podczas oczekiwania.",
                'price' => 1500,
                'price_unit' => 'month',
                'width' => 1.20,
                'height' => 1.80,
                'variant' => 'double_sided',
                'traffic_intensity' => 'high',
                'status' => 'active',
                'has_backlight' => true,
            ],
            [
                'title' => 'Telebim przy Olivia Business Centre',
                'type' => 'led_screen',
                'location' => 'Al. Grunwaldzka 470',
                'city' => 'Gdańsk',
                'region' => 'pomorskie',
                'latitude' => 54.4031,
                'longitude' => 18.5721,
                'description' => "Szukasz bogatych studentów i IT-mordek? :) Mamy z zespolem duży ekran prosto koło Olivia Business Centre.",
                'price' => 4900,
                'price_unit' => 'month',
                'width' => 6.00,
                'height' => 4.00,
                'resolution' => '1280x720',
                'traffic_intensity' => 'high',
                'status' => 'active',
                'has_backlight' => true,
            ],
            [
                'title' => 'Szeroki baner Obwodnica S6',
                'type' => 'banner',
                'location' => 'Węzeł Karczemki',
                'city' => 'Gdańsk',
                'region' => 'pomorskie',
                'latitude' => 54.3392,
                'longitude' => 18.5204,
                'description' => "Czołem, rozpinamy co miesiąc duże szmaty (banery) na wiadukcie obwodnicy Mój ojciec jest administratorem tej bariery. Świetne miejsce na pokazanie się tir-owcom i całej Pólnocy Polski wracającej znad morza.",
                'price' => 2000,
                'price_unit' => 'month',
                'width' => 10.00,
                'height' => 2.00,
                'traffic_intensity' => 'high',
                'status' => 'active',
                'has_backlight' => false,
            ],

            // ================= ŁÓDŹ / KATOWICE =================
            [
                'title' => 'Elegancki panel - Piotrkowska',
                'type' => 'citylight',
                'location' => 'ul. Piotrkowska 100',
                'city' => 'Łódź',
                'region' => 'lodzkie',
                'latitude' => 51.7631,
                'longitude' => 19.4578,
                'description' => "Jesteś marką premium? To tu musisz być. Citylight w najdroższej częścideptaka miasta Łodzi, witryna od razu widoczna.",
                'price' => 1200,
                'price_unit' => 'month',
                'width' => 1.20,
                'height' => 1.80,
                'variant' => 'double_sided',
                'traffic_intensity' => 'high',
                'status' => 'active',
                'has_backlight' => true,
            ],
            [
                'title' => 'Billboard koło Spodka',
                'type' => 'billboard',
                'location' => 'Rondo im. gen. Ziętka',
                'city' => 'Katowice',
                'region' => 'slaskie',
                'latitude' => 50.2642,
                'longitude' => 19.0232,
                'description' => "Wynajmę plakatowanie przy ogromnym rondzie i Spodku w Katowicach. Spory hałas imprezowy w okolicy i wieczne korki, więc każdy widzi zza chmurki smogu naszą blachę reklamową ;)",
                'price' => 4100,
                'price_unit' => 'month',
                'width' => 6.00,
                'height' => 3.00,
                'variant' => 'standard',
                'traffic_intensity' => 'high',
                'status' => 'active',
                'has_backlight' => true,
            ]
        ];

        foreach ($ads as $ad) {
            $baseData = [
                'owner_email' => 'admin@reklamap.pl',
                'phone' => '', // MUST BE EMPTY SO PHONE IS HIDDEN
                'contact_preference' => 'email',
                'is_active' => true,
                'is_verified' => true,
                'offer_type' => fake()->randomElement(['owner', 'agency', 'sublease']),
                'price_includes_print' => fake()->boolean(),
                'price_includes_mounting' => fake()->boolean(),
                'has_vat_invoice' => true,
                'has_image' => false,
                'images' => [],
                'orientation' => isset($ad['width'], $ad['height']) 
                    ? ($ad['width'] >= $ad['height'] ? 'horizontal' : 'vertical') 
                    : 'horizontal',
                'slug' => Str::slug($ad['title'])
            ];

            $finalData = array_merge($baseData, $ad);
            // Ensure no matter what we clear these two
            $finalData['contact_preference'] = 'email';
            $finalData['phone'] = ''; 

            Advertisement::updateOrCreate(
                ['slug' => $finalData['slug']],
                $finalData
            );
        }
    }
}
